### ISSUE TITLE
Recipes lack statements of obligation

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#101]
To extend the recipe metaphor: its like we have lots of descriptions of the ingredients typically in a dish but no clear statement of which ones to put together.

To abandon the metaphor: I can't see which of the possible bits of JSON MUST/SHOULD/MAY be there.

(one problem this creates is that it is hard to know how to robustly query for kinds of activity. For example, can I rely on context.platform being there?)

**Comment by wilmTap** [comment]
Shall we just make another column in the tables for each property and indicate cardinality, [1 1] style?

**Comment by wilmTap** [comment]
Accepted

**Comment by ds10** [comment]
I've added these to the new common_statements page. I put a new column in but I'm not sure the cardinality style works. I think having just  MUST/SHOULD/MAY  in the column would work better?

**Comment by ds10** [comment]
Wilberts way of doing this seems to work best, put cardinality in the original column and anything extra in the description, Wilbert will update this.

We need to check the cardinality though..
