### ISSUE TITLE
Bb and Moodle Examples are out of sync with spec

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#102]
For example assignment submitted has an old duedate syntax.

Suggest the recipes should be (one of):
- updated
- deleted
- organised under an explicit version number

**Comment by wilmTap** [comment]
I suggest doing both explicit versioning in the documentation and updating the examples.

The version can be indicated by the new recipeVersion property in the code, and versioning the links in the recipe pages in the documentation.

**Comment by wilmTap** [comment]
Will alert @miro and @michaelwebbjisc once the documentation for v.05 is done
