### ISSUE TITLE
Cryptic common identifiers

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#103]
I see quite a few like "Common entity identifier: Context.A"

... but it isn't clear what function these statements have. e.g. I can't find something identified by "Context.A", but infer that recipes which contain this have a common pattern for context. Common patterns are good, but inferences bad...  More overt wording would help (actually, I would like to see a single place for the normative wording of common patterns; even if there is some duplication of text, this saves us from ambiguity in case of discrepancies arising from edit-slips.

**Comment by wilmTap** [comment]
Would it help if we included something like:

> Common entity identifier: Actor_A
> 
> [Find all other instances where this entity is used in the Jisc profile](https://github.com/jiscdev/xapi/search?utf8=%E2%9C%93&q=Verb_A).

Note that this requires a change in the identifier form (github search disregards ".")

We've considered making separate pages for common entities in the past, and came to the conclusion that they probably confuse more than that they help for most of our audience. Happy to reconsider, though.

**Comment by wilmTap** [comment]
Adam to comment.

**Comment by arc12** [comment]
See PR #111

**Comment by arc12** [comment]
BTW - also several edits adding statements of obligation and expansion of descriptions of expected useage.

**Comment by ds10** [comment]
I've changed each recipe to look like this example and on the whole I think it works better, particularly in keeping the whole thing in sync. I think I need to case my eye over it again to check I haven't broken links etc.

**Comment by ds10** [comment]
Common entity identifiers to remove dot Context.A ->ContextA
