### ISSUE TITLE
courseArea documentation (vocabularies page)

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#106]
Under section 4.1 on Vocabularies.md

Link to "CourseArea properties" is non-functional

I feel we need more clarity on the content of the extension; "JSON Object with properties vle_mod_id and/or id" doesn't explain what these properties mean.

**Comment by arc12** [comment]
sorry - I see there is some explanation of vle_mod_id lower down. I still think this needs some improvement tho. For example. I think that the vle_mod_id wording should explain that this is an idenfier which is known in the SRS. i.e. its not just the semantics which are defined in the UDD but that the identifier matches LRW-UDD data. Also, I think the wording should indicate that, if this information is known in the VLE then the xAPI statement SHOULD include it (the current wording makes it appear to be wholly plugin-dependent and optional).

I think we also need some clarity on what the entity means. Key issue here is that what comes in the "id" field must be generally mappable to course/module instances in UDD-land.

[BTW - I'm a bit concerned that we don't seem to have a demonstrable VLE-SRS mapping strategy in the infrastructure yet - not a spec issue I know]

**Comment by wilmTap** [comment]
It seems to me that there are two issues:

1. How to make the property more required
2. How to improve the wording.

For 1: we could make it fully required- this is just an identifier for the courseArea after all, the linking to a module happens elsewhere. That is: the VLE doesn't need to know about that.

Re. 2: "http://xapi.jisc.ac.uk/extensions/vle_mod_id is a courseArea identifier. It is used in the [module_VLE_map entity](https://github.com/jiscdev/analytics-udd/blob/master/udd/module_vle_map.md) of the UDD to link module instances to course areas. Note that several module instances (as identified by their UDD MOD_INSTANCE_ID) can link to one courseArea"
