### ISSUE TITLE
loggedin IRI discrepancy

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#107]
Ref: https://github.com/jiscdev/xapi/blob/master/vocabulary.md#verbs
The wording on Vocabulary.md indicates the IRI is "https://brindlewaye.com/xAPITerms/verbs/loggedin" but the example indicates "https://brindlewaye.com/xAPITerms/verbs/loggedin/"

While these may have identical effect in a HTTP request, they are clearly different strings and so queries to the LRW using one don't retrieve the other. :-(

Based on the (old) examples in this repo, the Bb and Moodle plugin developers seem to have chosen differently. Double :-(

**Comment by wilmTap** [comment]
https://brindlewaye.com/xAPITerms/verbs/loggedin is the canonical one... I'll fix in the documentation, I fear @michaelwebbjisc needs to fix it in the moodle plugin.
