### ISSUE TITLE
Eduroam Access Point Association

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#109]
Would a recipe be useful to record when a students device makes an association to an access point?  This is not logging in to Eduroam but a device association with a particular access point.

The information that could be recorded are Student ID, mac address of device, mac address of access point, timestamp of association.  If the location of the access points is known, this could provide some useful spatial analytics.

**Comment by wilmTap** [comment]
I think it could potentially be an interesting recipe, but the question is whether a) institutions are likely to be able to get at that data, and b) whether they are likely to be able to store that data with the Jisc analytics LRW, given data protection constraints. 

It'd also be good to think about what analytics goals such data could support. For example, is access point logs more about estate utilisation, or is there a connection with student attainment?

**Comment by garemoko** [comment]
It could be an indicator of engagement which could be a leading indicator of retention.

**Comment by alleycat58uk** [comment]
**In terms of the practicalities** the data is stored both for legal and network management purposes.  In our case we are meeting with our network manager to see how we can access the data before it is lost as we have finite space and overwrite the oldest records.

In terms of the data protection, the data sharing agreement and our agreement with the students covers this.  This may not be the case for many institutions though.

**In terms of analytic goals** a few of the scenarios I have in mind are:
- Are we providing the right level of support in distinct given areas?  knowing the breakdown of students in each area would help get this right.
- Are we spending money on the right type of space for the students that use it?  Do we have the right resources/facilities available?
- Are we targeting messages/information in the right places?  This would be much easier if we knew which students congregated in which spaces.

These are all factors that can have an effect on retention, attainment and satisfaction.

I have forked the repo so will have a go at putting a recipe together if thats ok.

**Comment by alleycat58uk** [comment]
Can I ask, what is the intention for [http://xapi.jisc.ac.uk](http://xapi.jisc.ac.uk)?  I've seen it mentioned in various other recipes/examples but the domain doesn't resolve.

**Comment by ds10** [comment]
thanks for the pull request #114 . I have merged this in to the 0.5 branch, I will take a look and bring it up at the next working group stand up meeting. I'll report back soon and hopefully get this in to the 0.5 release.

**Comment by ds10** [comment]
@alleycat58uk Thanks again for submitting, I've had a quick look at this and updated the recipe to include things that I think are required by the spec, I've changed some of the values where I think they were invalid too.

I'll have another look with @wilmTap and bring it up at our next team call. It looks a lot like the logged in to VLE recipe, would the logged in verb be appropriate here?

It is still very much in draft, so comment and feel free to tell me I've got it completely wrong! It is in the 0.5 branch: https://github.com/jiscdev/xapi/blob/v0.5/recipes/wifi-association.md

**Comment by alleycat58uk** [comment]
@ds10 Will have a look through the changes at the weekend and let you know.

As far as the logged in verb I struggled with this one.  Originally I wanted associated with to keep things semantically accurate but that wasn't available.  The reason I stayed away from logged in is because there is actually a separate action of logging into the Wifi which is performed once.  The Actor is then free to roam on the network associating to and disassociating from access points as they go.  This act of initially logging on to the Wifi may also be useful at some point as it would show Sconul access uptake of distance learners etc.

I'm happy to be guided here on the appropriate verb to use, we are just keen to progress as we are currently piloting the collection of data to ascertain practical collection methods, storage requirements etc.

Thanks for the patiences, it's a learning curve.

**Comment by ds10** [comment]
> The Actor is then free to roam on the network associating to and disassociating from access points as they go

@alleycat58uk thanks for this. I think team talked about a 'presence' recipe, so perhaps that is the way they want to go. I was on leave during that conversation but I will follow it up

**Comment by alleycat58uk** [comment]
@ds10 a 'presence' recipe where presence on the WIFi network would be one specific concrete example.  Makes sense to me as long as it allows the capture of the 4 pieces of information detailed in the pull request.

Let me know how the talk goes and I'll be happy to amend as necessary.

**Comment by ds10** [comment]
@alleycat58uk I've changed the recipe quite a bit - if you want to talk about any of the changes and want to skype thats fine.

It looks like this will be broadened out to be a presence recipe, but there is quite a bit of discussion and it is still in draft, new developments will appear as tickets on here (such as #117 )

**Comment by arc12** [comment]
@ds10 @wilmTap - thinking about "presence". I think if we do encompass wifiAP connection in a presence recipe, it should be a "physical presence" recipe to differentiate from "online presence".

**Comment by alleycat58uk** [comment]
@ds10 skype would be good

**Comment by ds10** [comment]
I've had a chat with @alleycat58uk from University of Gloucestershire  who has looked in to the data they collect. Here are my notes, hopefully Paul will correct me if I am wrong. I'll update the recipe based in the notes.

- The Networks syslogs didn't log student id's so there were some steps to create something with the network management software, we don't know what software other Universities use, but UoG use a major vendor
-The software collects two types of data authentication & association, (may need correcting on this) authentication is when a student authenticates (through eduroam) on a access point, whereas association is connection to the access point without authirization. The authentication logs have student ids and are therefore what they are using.
-Authentication logs are made up of accesspoint checks to see if the client is allowed to be authenticated on the network. This means there is no 'log out' but you do get a picture of a student moving around the campus as they keep getting authenticated.
-There are 3 easy to use pieces of information in each line in the log: who (student id), where (id of acesss point), when
-Paul is not sure about mac addresses yet and thinks there may be a bit of tweaking to get this data

I'll update the recipe to reflect what we know from Paul's logs and what was discussed on the last call. 

It does seem that this recipe might have quite a few technical properties and 'if you don't have this use that' bits. I know we have gone back and forth with this, but I am wondering if this should be solely a wifi association recipe which is part of a series of recipes?

**Comment by ds10** [comment]
From internal Cetis call for next monday call:

* Does this become wifi authentication recipe belonging to a series of physical presence recipes. Others may be library card etc.
* Or do we still want a general physical presence recipe even though this recipe has quite a few specific bits etc

Current recipes:
https://github.com/jiscdev/xapi/blob/0.6/recipes/wifi-association.md
https://github.com/jiscdev/xapi/blob/0.6/recipes/wifi-dissociation.md

will impact on #118

**Comment by ds10** [comment]
Perhaps the issue here is the same as discussed in #126 (regarding intervention recipes ) . Do presence recipes have  whitelist/blacklist of verbs or do we have single verb for them all with whatever magic workaround we come up with for the interventions.

**Comment by ds10** [comment]
After some planning meetings update:

The aim for the repository in the short term is to go 'wide' with the xapi recipes, which means not going in to too much technical details for now and trying to get 'high level' recipes that may be drawn from various data sources. The way I understand  it now is that he information here would go in to a presence recipe for now and down the line we can worry about technical details.

Proposals/discussion for Monday calll::

- We keep the wifi-association/dissociation recipes but on the backburner for now

- New 'physical presence' recipe that is quite slimmed down

- We ask  @alleycat58uk very nicely if we can have a sample of the data he has access too. Small annoymised example would be great.

- From this sample we create a generic CSV/TSV example that captures the core things needed for physical and can be hopefully generated from other sources (not just wifi) - (The reasoning for this is that institutions will be generating these for Jisc in early days)

**Comment by ds10** [comment]
From Monday call:

- Yes, follow the new 'wide approach'. Keep current examples on backburner
