### ISSUE TITLE
Presence recipe macaddress issues

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#117]
The two mac addresses for object and context - these need me to different. macadress extension also needs adding to vocab.

**Comment by arc12** [comment]
I suspect the object is the AP and the context is the client device is the way to go.
Recipe needs to be ultra-clear.

**Comment by alleycat58uk** [comment]
Yes @arc12 that is the reason for the 2 mac addresses in object and context.  The reasoning is Object (AP mac) gives a physical location and Context (client device) yields the number of devices an Actor (user/patron/customer ...) has.
