### ISSUE TITLE
New Recipe: Intervention

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#121]

**Comment by arc12** [comment]
May I suggest that, before David puts more meat on these bones, that we get ourselves clear on the typical lifecycle which this recipe fits into. I suspect that we might also think about whether "intervention" is the right terminology. The word has been used rather loosly and I think we should only use it to refer to a record of an act by a person with an intention to help. We should maybe also think about whether a teacher correcting work is logically also an "intervention", and clarify whether this is in scope.

The typical lifecycle should be discernable in the SSP workflow, and we can also indicate the Tribal Student Insight - Student Information Desk flow. The key thing is to be clear where in a case management scenario the recipe sits, and whether there should be a series of recipes.

**Comment by ds10** [comment]
Agree with @arc12 . I have left the 'interventon' draft without any meat intentionally as it wasn't fleshed out much at the last meeting and I don't have experience with the intervention systems.

The current draft has the system as the actor issuing an intervention, with instructor in the context as the person issuing it, but from the way I think you are describing the act is by the person intending to help, so the actor is the person making the intervention and the intervention system is the context.

Could do with some guidance going forward

**Comment by arc12** [comment]
Our related application is:
http://www.tribalgroup.com/higher-education/customer-services-software/student-information-desk/

**Comment by ds10** [comment]
from ticket #126 via @arc12 but belongs here;


> 
> @ds10 it might work, it depends on what the verb really is. As I've said before I dont like "intervened"; its too wooly.
> 
> Things we might record.
> tutor - interviewed - student (an actual meeting for pastoral care or guidance)
> tutor - raised a concern about - student (equivalent to a LAP alert?)
> tutor - assigned remedial work to - student
> 
> These feel less awkward than: tutor - intervened on - student
>

**Comment by ds10** [comment]
From an internal Cetis call, questions for monday:

- Is this the same issue as #126, does having a student as the actor bring up activity when they are being acted on. If so, what is the approach for 126 and does it fit here.

**Comment by alanepaull** [comment]
From Monday 5 Dec call:

1. Generic 'intervene' verb needed, so that these can be queried easily.
2. More details about the type of intervention could be put in the Context.
3. Create some examples.

**Comment by arc12** [comment]
Ahh - I had mentally noted, from the call:
1. specific verbs needed
2, use context to somehow identify the umbrella, for ease of querying

Actually 1: I think querying is one issue, but reconstructing a sequence is really part of the desirable path.
Actually 2: the "umbrella" could well simply be to know that the statements came from a "case management" system, i.e. via a minted URI for that kind of application.

Another issue here is that some cases might have particulary confidential interactions which should not be propagated to the LRW.

**Comment by alanepaull** [comment]
Yes, we're thinking that using Context for detail is counter to the essence of Context - because Context is more to do with a 'wider system' than it is to do with a narrower one.  So, Context for the umbrella seems in line with the xAPI meaning.

However, that still leaves the difficulty of recording the detail, if that's required.  One could imagine some form of extra 'source verb' type of construct (like a 'source data' in UDD), but I'm not yet sure how or whether that would work or be desirable. 

Examples needed, I think.  How many realistically different intervention verbs might there be?

**Comment by arc12** [comment]
@alanepaull I suspect not very many verbs in the recipe. My guess is that case management tools are quite customisable and that there is a potentially unbounded set of possibilities. It would be nice to think that many of these are nuances over a small set of acts which are functionally very similar. e.g. the making of an appointment to see an advisor, and the attending of the event. e.g. a communication by some medium from or to a student. e.g. the raising of a concern/alert by a person or machine.

The nuance might be important from a pastoral care POV, but proliferation will force the data processors to ignore the nuances (IMO)

**Comment by ds10** [comment]
@alanepaull @arc12 

My notes seemed to have a collection of different (and contradictory) ways we could go forward. I've put together some drafts to talk about. Opened a ticket for the skype call  at #130

**Comment by arc12** [comment]
@ds10 - are those 01:00 and 03:00 ? I'll be in bed!

**Comment by ds10** [comment]
@arc12 oops! I've changed the timings but it has broken your response, sorry!

**Comment by ds10** [comment]
Notes: Intervention recipe is likly to grow as the general as we write statement statement templates. The general approach to this (to not have an intervention verb) has been roughly decided and a rough 'interview' statement has been knocked up. Keeping this open for now as a reminder, as closed tickets #126 #130

**Comment by ds10** [comment]
@pbailey64 was asing where we were with intervention templates. Adam, myself, Dai, Lee and Alan had a look at this late last year. We had 3 candidates which can be found in the interventions branch, in the end we went with [candidate b](https://github.com/jiscdev/xapi/blob/feature-intervention/recipes/intervention/intervention_candidate_b.md) . A fleshed out example can be found in an [interview intervention](https://github.com/jiscdev/xapi/blob/feature-intervention/recipes/intervention/interviewed.md): 

The notes from candidate B say:

-The actor is the alerting system or tutor
-Specific verbs are used in the verb entity to describe the intervention
-Object contains the student
-we use context to somehow identify the umbrella, for ease of querying

I think this was put on the backburner to work on requirements for 1.0. I think it needs input from domain experts on what interventions can take place and what the iri are etc.

**Comment by ds10** [comment]
A few weeks ago we decided this was to be revisited looking at some new data. I think @michaelwebbjisc was going to post some headers?

**Comment by ds10** [comment]
This doesn't have a milestone next to it, but the last comments sugguest @michaelwebbjisc had some new data for this? Is it possible to have this. Is 1.1 a milestone for this?

**Comment by leebaylis** [comment]
I had a conversation with Greenwich last week where they wanted to classify things like giving students a skills course or an induction as an intervention even though it wouldn't have been necessarily triggered by anything. They were interested in capturing it as a blanket intervention *before* they started assessing whether or not to determine who gets it based on other data...

**Comment by ds10** [comment]
See ticket #230. 3 Intervention recipes to be created based on previous feature branch but working backwards from TSV definitions first.
