### ISSUE TITLE
Helpdesk issue raised

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#125]
I think a recipe for issues being raised on a helpdesk would be useful as it could be an indicator for a number of things:
- issues raised show a level of engagement.  Students are reporting issues to get them resolved rather than ignoring them or finding a work around.
- timing of the issue could have a greater impact if it is near assignment hand in/submission.
- do particular cohorts raise particular issues over and above the norm?  This may indicate a need for improved provision in terms of physical hardware, processes, user education etc.

**Comment by ds10** [comment]
@alleycat58uk do you have examples of (anon) data and the systems that produce them? We could have a stab
