### ISSUE TITLE
Recipes when the student is really the actor but is acted upon

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#126]
We've got a couple of recipes where the student is really a recipient.  The ones that come to mind out assessment marks, when really the tutor is the actor, and the student is the recipient:

https://github.com/jiscdev/xapi/blob/master/recipes/assignment-graded.md

and alerting:

https://github.com/jiscdev/xapi/blob/master/lap/apereo/model_output.md

when the actor is really the LAP.

These cause problems when showing student activity, as the student doesn't actually do anything.

I'm not sure if there is a correct way of showing recipient, but I've experimented with adding a recipient to the context, which works fine for reporting.  Here's a LAP/altering example:

{
  "version":"1.0.0",
  "actor":{
    "objectType":"Agent",
    "account":{
      "name":"PseudoLAPv0",
      "homePage":"http://jisc.ac.uk"
    }
  },
  "verb":{
    "id":"http://xapi.jisc.ac.uk/verbs/predicted",
    "display":{
      "en-GB":"predicted",
      "en-US":"predicted"
    }
  },
  "object":{
    "objectType":"Activity",
    "id":"https://lap.jisc.ac.uk/earlyAlert/unicon/id",
    "definition":{
      "type":"http://activitystrea.ms/schema/1.0/alert",
      "name":{
        "en-GB":"An early alert",
        "en-US":"An early alert"
      },
      "description":{
        "en-GB":"An early alert",
        "en-US":"An early alert"
      },
      "moreInfo":"http://jisc.ac.uk",
      "extensions":{
        "https://lap.jisc.ac.uk/earlyAlert/type":"JiscPseudoLAP"
      }
    }
  },
  "context":{
    "extensions": {
              "http://xapi.jisc.ac.uk/courseArea": {
                  "http://xapi.jisc.ac.uk/modinstanceid": "**MOD_INSTANCE_ID**",
                  "id":"https://github.com/jiscdev/analytics-udd/blob/master/predictive-core.md#mod_instance/**MOD_INSTANCE_ID**"
                },
                "http://xapi.jisc.ac.uk/recipient": {
                    "http://xapi.jisc.ac.uk/studentid": "**STUDENTID**",
                    "id":"**STUDENTHOME**/**STUDENTID**"
                  }
                },
    "contextActivities":{
      "grouping":[
        {
          "objectType":"Activity",
          "id":"https://github.com/jiscdev/analytics-udd/blob/master/predictive-core.md#mod_instance/**MOD_INSTANCE_ID**",
          "definition":{
            "type":"http://adlnet.gov/expapi/activities/module",
            "description":{
              "en":"Jisc Module Instance"
            },
            "name":{
              "en":"Jisc Module Instance"
            },
            "extensions":{
              "https://lap.jisc.ac.uk/taxonomy":"MOD_INSTANCE"
            }
          }
        }
      ]
    }
  },
  "timestamp":"**TIMESTAMP**",
  "result":{
    "extensions":{
      "https://lap.jisc.ac.uk/earlyAlert/score":"**RISK**",
      "https://lap.jisc.ac.uk/earlyAlert/Background":"**METRIC1**",
      "https://lap.jisc.ac.uk/earlyAlert/VirtualEngagement": "**METRIC2**",
      "https://lap.jisc.ac.uk/earlyAlert/Achievements": "**METRIC3**"
    }
  },
  "authority":{
    "objectType":"Agent",
    "name":"Unicon",
    "mbox":"mailto:hello@unicon.net"
  }
}

**Comment by gryglbrt** [comment]
Yes, that makes sense and I see how it could be an issue. I don't think it will be a problem to update the code that sends the xAPI statement to the LRW with this but it may take a little longer to rework the queries that pull the appropriate statements from the LRW (e.g., for the dashboard).

**Comment by amason** [comment]
https://jisc-la.atlassian.net/browse/JLA-670 has been written to address this. I'll note the github issue when this is complete.

**Comment by arc12** [comment]
I think the two cases are different.

The current assignment scored recipe completes a cycle which starts with the student. I think it is reasonable to record that the student (as actor) scored...
Doing so makes it straight-forward to work with the cycle, with a fairly clean query.
If we care about generating stats that represent real activity then we can use the verb to filter on.
I would like to see the agent remaining as the student for all assignment statements.

The alerting case is arguably different, not matching the above points. It is also more tenuously linked to recording the actions and outcomes of a learning activity, so is arguably something which is being put into the xAPI part of the LRW as a convenience. Its not really a learning record.

I note that xAPI spec allows object to be an agent. That would be a neat way of expressing the identity of the individual about whom the alert refers to.

**Comment by ds10** [comment]
I have been thinking about this because the student is acted upon in a few of our draft recipes, such as intervened in 0.6: https://github.com/jiscdev/xapi/blob/0.6/recipes/intervention.md

I had started the draft as the object being an agent like @arc12 points out. The problem I have been thinking about is that I am not sure that the student is the object being acted upon,  sleepless nights thinking  'does it sound right to say tutor intervened on a student'? and wondering does the tutor create an intervention on an instance in the academic tutoring system instead with the student somewhere in the context.

I think this is the same question we have for the model output example? PseudoLAPv0 is making a prediction on the alert, so the object is the activity alert and not the student. Then we use the method @michaelwebbjisc has to put student in context, is that right?

**Comment by arc12** [comment]
@ds10 it might work, it depends on what the verb really is. As I've said before I dont like "intervened"; its too wooly.

Things we might record.
tutor - interviewed - student (an actual meeting for pastoral care or guidance)
tutor - raised a concern about - student (equivalent to a LAP alert?)
tutor - assigned remedial work to - student

These feel less awkward than: tutor - intervened on - student

**Comment by ds10** [comment]
@arc12 I think I would feel more comfortable doing it that way, so the issue there is creating a taxonomy of things we might record for intervention (the verbs) and leave the student as the object. Otherwise the detail has to go in the context and it has a different 'style' to other recipes.

Still leaves the actions in this issue:

- Do we want to change the model output to Micheal example

- Are people happy with the graded recipe or does that want changing?

**Comment by michaelwebbjisc** [comment]
The problem with having the student as the actor on the graded, is we get an activity event, even though they haven't done anything.  It makes displaying student activity data a real pain, as we have to filter on every even type.   

The student activity we'd actually want is that they had looked at the grade.

I really think we need a principle that the person has to actually do something to be an actor in an event.   

Incidentally I first picked this up when looking at why the moodle plugin was doing what I expected for assessments - it's because it behaves in the way I'm proposing.

@arc12 what would be the practical impact on your work if we made the change?

**Comment by arc12** [comment]
Michael -
I think an audio chat would be best...

some notes tho:
1. "scored" is an established xapi verb (along with mastered, passed) which have the semantics of actor = the learner
2.  I would expect you'll need to filter, segment, or weight activity in any case as the spectrum of kinds of activity increases.
3. practical impact is less architecturally tidy code. In general we'll be wanting to flatten a series of events into a set of statistics*, which implies fetching the events which pertain to particular kind  of activity (e.g. the assignment lifecycle). Being able to use a single query sounds like a nice-to-have but if we can have a unified query pattern which works across the numerous sets of statistics, we'll be much better off for maintainability and quality.

* - quite focussed around e.g. assignments, quizzes, forums use, resource use, attendance, WiFi AP, library access, eJournals...

**Comment by ds10** [comment]
Does this want to be added to the agenda for our next Monday call as semantics would be relevant for other recipes?

**Comment by amason** [comment]
Hi all, just so everyone has the latest update...Unicon has made the change on our end. You won't have a way to see it in action until we get all the final output stuff completed though. 

Let me know if any questions. 

Amanda

**Comment by michaelwebbjisc** [comment]
OK, I have found an example that supports @arc12  view, which is this one:

http://xapi.vocab.pub/datasets/adl/#satisfied

So in this example, it's clearly indicated that actor is passive in the process, and the actual thing doing the active is some other authority,

This still brings us to the original issue - i think we need a straightforward way of identifying the statements when actor actually does something without working through every verb.

What other options can people think off?  Adding a context extension to act as a flag for passive statement?  

Also, picking up on the interventions, again we need a single element that will pull back all interventions. So either the verb is intervened and the context gives more detail, on the contexts needs an extension to show its an extension.

**Comment by arc12** [comment]
> This still brings us to the original issue - i think we need a straightforward way of identifying the statements when actor actually does something without working through every verb.
> 
> What other options can people think off?

Whitelisting and blacklisting verbs ;-)
Bite the bullet!

> Also, picking up on the interventions, again we need a single element that will pull back all 
> interventions. So either the verb is intervened and the context gives more detail, on the contexts needs
> an extension to show its an extension.

I'd be inclined to use "platform": "SSP" (or whatever). I think HT2 put an index on statement.platform. It makes for a neat way of pulling back all (or only) interventions, attendance data, wifi connects etc. In fact, I suggest we make this use of "platform" be policy. Doing so will also help us to use common verbs across e.g. several aspects of presence, allowing us to query both generally or with specificity to a platform, and to do so with simplicity.

**Comment by michaelwebbjisc** [comment]
Not keen in platform - that's moving away from our our idea that the activity is the same what ever the platform, but it could be platform type.  People would have to know all the different platforms

I still can't believe we can't come up with a better idea than black/whitelisting.  It's just adding complication!

So in all of these I'm trying to simplify things for newbies using APIs.  I want to make it easier for non-specialist people to find a away in.   I want people to be able to pull out all the things a student does in a simple statement, same for interventions.   

I think that's a pretty import aim - so lets try to crack this one!

**Comment by michaelwebbjisc** [comment]
@ds10 yes - can we pick this up on the call on Monday.  But lets see how far we can get online before we get to monday.

**Comment by arc12** [comment]
@michaelwebbjisc 
re platform: fair enough. its not an issue for us because we're always configuring the data pipeline for a specific set of client data sources. We (the xAPI recipes "we") already have "http://id.tincanapi.com/activitytype/lms" (and will doubtless coin more) to qualify the kind of application logged into, so we could use the same vocabulary to identify the kind of platform using a simple extension in context.

Re "compliction": I'm a fan of being explicit about what I want, and avoiding e,g, the discovery that some random crap or R&D got pushed into the LRW and treated as real activity ARGHH only some time after its got to the end users. Whitelisting is your friend... to this end, all of our queries match either (verb or object.definition.type) and platform.

Re simple statements: absolutely a good principle. It should be as simple as possible but no simpler! Complexity in forming statents, querying for them, and handling the results from the query is worth some time to avoid. Its not just non-specialists... the fewer the ifs, buts, caveats, etc the more maintainable and bug-free everyone's code will be.

**Comment by michaelwebbjisc** [comment]
@arc12 I think the think to consider is that the change i'm suggesting doesn't actually stop you doing what you want.

**Comment by michaelwebbjisc** [comment]
So...here's another approach.

If we look at  the Assignment recipe we he an instructor in the recipe.

        "instructor": {
            "objectType": "Agent",
            "name": "instructor",
            "account": {
                "name": "Ray Keenan",
                "homePage": "http://localhost/moodle"
            },

So another approach would we to ensure that for all activity where the student isn't the instigator there must be an instructor.

So for the early alert example, instead of the approach I suggested, the student would remain the actor, and the LAP would become the instructor.

That fulfils my criteria of having a single query to identify passive an active activity.

This doesn't stop anyone whitelisting as admin suggested, but it gives another simple approach.

Thoughts?  It that stretching the concept of the instructor too far?

**Comment by gryglbrt** [comment]
I think that does not fit the intent of instructor so yes it stretches the concept too far. context seems to be the most appropriate place to me.

**Comment by ds10** [comment]
From an internal Cetis call, two questions for monday:

- Have the made  to the model output xAPI as suggested by in the top post already been made? If so does @gryglbrt want to do a pull request of the current output.
* What is the approach going forward if students aren't acting but they are acted on - this might knock on affect for intervention and presence recipes.

**Comment by amason** [comment]
Hi - Unicon has made the changes and we will do a pull request on Monday.

As for bullet #2, that's a Michael question I believe.

Thanks!

**Comment by ds10** [comment]
Monday Update: 
Experiment with recipes that the student has been acted on with the student staying as the actor and a flag so they can be grouped together. The approach has to be the same across recipes, for example the intervention and assignment graded the actor is acted upon. Des

- We may also want examples where actor where student is acted upon goes in to the object. This might be the case for the intervention recipes. In the intervention case we might want a single verb for intervention with the instructor/system as actor with context containing more info.

Follow up with a skype call among interested parties and attempt to get something in place during January

**Comment by alanepaull** [comment]
Please could interested parties indicate here.  Then we can set up a Skype call in advance before diaries get filled up.
Thanks in advance!

**Comment by arc12** [comment]
interested

**Comment by amason** [comment]
Just a heads up to everyone: Pull request is done.

https://github.com/jiscdev/xapi/pull/128

**Comment by ds10** [comment]
@amason @gryglbrt . Thanks, merged the request and solved conflicts.
