### ISSUE TITLE
Add License information to xapi repo

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#127]
The UDD is licensed under a Creative Commons Attribution 4.0, but no license is present in this xapi repository. I have a memory that this was to be apache2? This is on my mind as we start thinking about the ways we might want to work with other projects/people in the same space.

Question: Should a license be added to this work, am I right in thinking we've spoke about this being apache2

**Comment by ds10** [comment]
From monday call:

- Yes - Apache 2 since this is what xAPI uses

**Comment by ds10** [comment]
@michaelwebbjisc can you confirm what should go in to the licence?

Github has a option that adds a license to the  repository. I've used it to automagically create the license: https://github.com/jiscdev/xapi/blob/master/LICENSE

It leaves out important information in Line 189: Copyright {yyyy} {name of copyright owner}

Can you advice on what Jisc would want here?

**Comment by alleycat58uk** [comment]
An option to copyright/left is to choose public domain.  Are there reasons you need to copyright/left?

**Comment by ds10** [comment]
I believe the udd is CC by Attribution and xapi is apache2. I wasn't part of the conversation where they were chosen, but I believe the reason for Apache2 over CCA4 on the XAPI is that the XAPI spec is also Apache2?
