### ISSUE TITLE
Specialist Software Use

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#134]
USW raised this at a recent meeting.
They have licence compliance software which monitors use (start and end times) of specialist software on their PCs. I believe this also includes location.

For some courses this is likely to be a better indicator of participation than VLE.

I think this would be a fairly stratightforward case as far as the spec goes:
- base on login/logout with some extension
- some comparable aspects to presence

BUT work will be needed to determine whether the information is generally available, and what the extensions to login should be to cover the 80%.

**Comment by gmoger-jisc** [comment]
Closing this as no longer active.
