### ISSUE TITLE
Attended learning activity template is under VLE

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#138]
Attended learning activity is listed under VLE, when it is actually a general attendance template rather than related to VLE, so should be under 'attendance and presence'

**Comment by ds10** [comment]
I think it already has been moved for version 0.6 : https://github.com/jiscdev/xapi/tree/0.6 , unless I am missing something?

It is under VLE for 0.5, but there isn't an attendance section there.

**Comment by michaelwebbjisc** [comment]
ah, yes, I'll close that !
