### ISSUE TITLE
Attendance - change context to match VLE

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#139]
I suggest we get this part of the context:

    "contextActivities":{
            "grouping":[
                {
                    "objectType":"Activity",
                    "id":"http://wicketkeeper.poppleton.ac.uk/modules/2016/sem1/psy101",
                    "definition":{
                        "type":"http://adlnet.gov/expapi/activities/module",
                        "name":{
                            "en":"Psychology 101"
                        },
                        "description":{
                            "en":"Entrance course for psychology."
                        }
                        "extensions":{
                            "http://xapi.jisc.ac.uk/uddModInstanceID" : "2016.sem1.psy101"
                            }
                    }
                }
            ]
        },

to follow the VLE pattern:

"context": {
        "platform": "Moodle",
        "extensions": {

        "http://xapi.jisc.ac.uk/courseArea": {
            "http://xapi.jisc.ac.uk/vle_mod_id": "LA101",
            "id":"http://moodle.data.alpha.jisc.ac.uk/course/view.php?id=4"
                    },

            "http://xapi.jisc.ac.uk/sessionId": "32456891"  ,
            "http://id.tincanapi.com/extension/ip-address": "10.3.3.48"
            "http://xapi.jisc.ac.uk/recipeVersion" : "vle_resource_viewedV1.3"

            }

        }

for consistency, and also to avoid needing to query items in arrays.

There's a second issue around '  "http://xapi.jisc.ac.uk/vle_mod_id ' and                             "http://xapi.jisc.ac.uk/uddModInstanceID" which I'll log separately, as it's related but not tied to this.

**Comment by arc12** [comment]
not sure I follow all of this but +1 for avoidance of arrays

I assume we DONT need IP and session.

**Comment by ds10** [comment]
recipe matches vle. IP, session etc not used
