### ISSUE TITLE
"http://xapi.jisc.ac.uk/vle_mod_id and "http://xapi.jisc.ac.uk/uddModInstanceID" in attendance

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#140]
This one is a little complicated.

In VLE templates we've got 

  "http://xapi.jisc.ac.uk/vle_mod_id '

to match to UDD, as it's the only identifier the VLE knows about.

In attendance we've got:

"http://xapi.jisc.ac.uk/uddModInstanceID" 

to match to the UDD.

The site affect of this is a single query, without looking for both values, won't find all the activity for a module.

We've got two options:

1) for all queries to look for both   "http://xapi.jisc.ac.uk/vle_mod_id ' and "http://xapi.jisc.ac.uk/uddModInstanceID" 

2) to include "http://xapi.jisc.ac.uk/vle_mod_id in the attendance template as well as http://xapi.jisc.ac.uk/uddModInstanceID

Option 2 is a bit intuitive, but I've realised a few bits the we have done rely on this (Study Goal etc).  I'm therefore going to propose a slightly odd solution.  We add http://xapi.jisc.ac.uk/vle_mod_id to the context, but depreciate it immediately.    That means that's we've got time to fix the code that uses vle_mod_id to look for any activity, but can start adding data activity data now and it work, using the (immediately depreciated) http://xapi.jisc.ac.uk/vle_mod_id

**Comment by MiroslavKratchounov** [comment]
In my opinion, option 1 is the less intrusive and requires no effort on the data collection and processing side. It will be more complicated on the data analytics side and may be confusing for users/analysts.
Option 2 is fine but I wonder what will be the impact from simply replacing http://xapi.jisc.ac.uk/vle_mod_id with http://xapi.jisc.ac.uk/uddModInstanceID. There are a few sites that Blackboard has already processed VLE activity data but if we implement the http://xapi.jisc.ac.uk/uddModInstanceID we can have a uniform approach across all recipes/templates. I’m not sure about Moodleroom sites, though. We are refactoring right now so for us it is the right time to make a change like this.

**Comment by michaelwebbjisc** [comment]
I don't think Blackboard and Moodle will necessarily know the uddModInstanceId, otherwise it would make things easier.  So vle_mod_id is, in effect, a something that moodle/blackboard know that can be used to look up the udd module instance later.  I guess the plugin/building block could do the extra lookup but I think that adds a lot of complication, and stops the plugin being about to work in insolation from the UDD.

**Comment by arc12** [comment]
Michael - to clarify...
I think you are saying the long term answer is "use option 1" but that you want to include a temporary synonym called "vle_mod_id", but which actually contains the UDD identifier, in the attendance recipe so that your code keeps working.

If so, could this be hidden? Not appear in the recipe but be automatically included at the time of statement generation.
If not, then I'm happy to go with the pre-deprecated language, although it will strike some as being a bit wierd.

**Comment by michaelwebbjisc** [comment]
Its not quite a synonym, as they behave in different ways.  vle_mod_id does a lookup to get the mod_instance_id but the the other one contains mod_instance_id directly.

Yes, it could be hidden.  I guess the reason to include it in the document is to help anyone in the future who might find them and wonder what they were.  I don't feel strongly about it though.

**Comment by ds10** [comment]
These are both currently in 0.6. Need to pick up on a monday call.

**Comment by ds10** [comment]
update from call 27th March.

Still have both in, this needs thinking about, asking people to reserve judgement for now
