### ISSUE TITLE
context.instructor.name should be removed the atttendance

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#141]
as we are using instructor.account.name

**Comment by ds10** [comment]
Just to double check: 

Agents in the VLE example (for example in login actor.name and actor.account.name) have both.  I understood they were different, that  .name is "Full name of the Agent" and account.name is "The unique id or name used to log in to this account".

So, for the attendence only the instructors account name is recorded?

account.name

**Comment by ds10** [comment]
nvm, just realised you sent sample attendence data in #137 and can answer my own question!

**Comment by ds10** [comment]
removed in 0.6 branch

**Comment by ds10** [comment]
Parked until @michaelwebbjisc remembers why this has been done. In 1.0 this has been removed as described in original post.
