### ISSUE TITLE
Additional information in attendance

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#142]
I'd like to add some extra info to the result and context.

In the result:

 it's whether the person was late, and what time they actually finished the activity (both optional.

In the context:

(the bits with **xx** are where the value goes).

activity type is 1 for lecture, 2 for seminar etc.  Would be good to standardise.
activity_max count is the total number of people that could have gone to the session
activity mandatory is whether it's optional or not.

            "http://xapi.jisc.ac.uk/activity_type_id":"**ACTIVITY_TYPE_ID**",
            "http://xapi.jisc.ac.uk/activity_max_count":"**ACTIVITY_MAX_COUNT**",
            "http://xapi.jisc.ac.uk/activity_mandatory":"**ACTIVITY_MANDATORY**",

**Comment by arc12** [comment]
See my comments on #137 
- lateness
- ACTIVITY_MAX_COUNT (which Michael describes differently here compared to Rob's spreadsheet)

**Comment by ds10** [comment]
1.6 branch:

added to context.extensions 

  "http://xapi.jisc.ac.uk/activity_type_id":"**ACTIVITY_TYPE_ID**",
 "http://xapi.jisc.ac.uk/activity_max_count":"**ACTIVITY_MAX_COUNT**",
  "http://xapi.jisc.ac.uk/activity_mandatory":"**ACTIVITY_MANDATORY**",

and

result.extensions:

"http://xapi.jisc.ac.uk/activity_late":

But I gather there is still some discussion reguarding lateness that we need to take up at face to face

**Comment by ds10** [comment]
From 27th March Monday code:

Add activity_type_description.
As part of xapi documentation have tabular form of data

**Comment by ds10** [comment]
From 27th March Monday chat:
add attendance category (left early, didn't attended but had note).
