### ISSUE TITLE
Attendance

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#143]
Final one of the day I think! (as you can tell I've been look at attendance data today!)

change start time and duration to start and end in the contxt

            "extensions":{
                "http://xapi.jisc.ac.uk/starttime": "**START_DATE_TIME**",
                "http://xapi.jisc.ac.uk/endtime" : "**END_DATE_TIME**"

this is to make it consistent with using a time to mark when the student actually finished the activity (so this is the intended start and end time).

**Comment by arc12** [comment]
I thought that is what we agreed on a call.
Use datetimes for planned start and end.
Compute duration if required.

Need to ensure the documentation is clear to differentiate planned event start/end and actual being/finish times for individual students

**Comment by michaelwebbjisc** [comment]
I couldn't quite remember, but template still had duration.

**Comment by ds10** [comment]
0.6 had planned-start-time and a planned-end-time, but in the object? Changed this as suggested in ealier commit.

**Comment by alanepaull** [comment]
Not sure if this is the right place for this comment; however.
In the example (attendance.md) object, we have
        "definition":{
            "type":"http://activitystrea.ms/schema/1.0/event",
            "name":{
                "en":"Lecture"
            },

I don't think that we're supposed to use event like that.  If we know the event is a lecture, shouldn't it be: "http://xapi.jisc.ac.uk/lecture"?

**Comment by ds10** [comment]
agree about  http://activitystrea.ms/schema/1.0/event . It should only ever be used if we don't know the type of event. Will change this
