### ISSUE TITLE
Blackboard Summative and Formative assessment activity data

### ISSUE THREAD

**Issue by MiroslavKratchounov** [jiscdev/xapi#144]
Currently the Blackboard assignment graded and assignment submitted recipes are limited to only Blackboard assignments summative data.  We can expand and include all assessment (summative and formative data) in the ETL process and push to LRW. Any thoughts, objections, concerns with this?

**Comment by arc12** [comment]
More assessment information is good.

BUT: I am sure we will want to know how to separate formal assignments with "high stakes" (and likely to be recorded in the Student Record System) from other assessments. Miro: what categories of assessment do you have?

Adam

**Comment by michaelwebbjisc** [comment]
Yes, that makes sense to me.

Agree with Adam we need to be able to separate them, but I've a feeling that might only be possible by linking some identifier in the assessment to external data (probably something on assessment_instance.

**Comment by arc12** [comment]
... and I have some doubts about achieving such a linkage in practice, based upon what I hear about current assessment management practices.

Presumably Miro can differentiate assessments somehow.... I think I just need to see some examples.

**Comment by MiroslavKratchounov** [comment]
In Blackboard we have the following assessment summative/formative types: Test, Survey, Assignment, Self and Peer Assessment, Discussions, Journal, Wiki, Blog. The level of adoption varies per institution. All those items will have a reference to vle_mod_id which should link to a record in SIS (uddModInstanceID).
I guess we will need a new extension to differentiate between the various assessment types. Something similar to course resource view types. If we implement this, we would need to create a new recipe or rename the current assignment recipes.

**Comment by arc12** [comment]
@MiroslavKratchounov - thanks. Which of those is used for the current recipe? Is there some overlap with the quiz activity type?

A simple approach would be to use the assignment-graded template:
- add an extension to refine the kind of assessment*
- for the assignment submitted/graded recipe to specify the URI to use for that refinement
- define a set of refinement URIs which can be applied by Bb and Moodle (maybe some would only be applicable to one VLE but there should be none which cannot be applied reliably to either VLE). I would exclude surveys (not a refinement of an assessment) but would like to see self or peer assessments, tests, and possibly assessment of online collaborative/social activity.

\* - ie. to refine this object.definition.type with some kind of extension
```
"object":{
        "objectType":"Activity",
        "id":"http://moodle.data.alpha.jisc.ac.uk/course/view.php?id=4",
        "definition":{
            "type":"http://adlnet.gov/expapi/activities/assessment",
```

**Comment by alanepaull** [comment]
Activity object definition and typing of assessments:

In Moodle there are several assessment-like activities, including assignment, choice, lesson, quiz, workshop, even 'database', which can include ratings of entries by teachers or students, or SCORM package. All of these can be graded. However, it's not clear whether slicing the data via self or peer assessments, online collaborative / social activity is possible. I suspect that we'll have to have a look at common practice, rather than what's possible in Moodle, because some of the activity types may get little practical usage.

We could use an extension to define the sub-types. It's likely that this will be VLE dependent, rather than generic. It might be worth investigating whether we can have generic sub-typing - like we would have in a UDD context for a vocabulary. 

Formative vs summative is still an open question at the moment. I think we'll need some data from universities and colleges to address that one.

**Comment by alanepaull** [comment]
Quizzes in Moodle are very flexible. They look much like the ADL definition of Assessment with Question. 

"An assessment is an activity type that determines a learner’s mastery of a particular subject area. An assessment typically has one or more questions."
"A question is typically part of an assessment and requires a response from the learner, a response that is then evaluated for correctness."

A quiz in Moodle is fundamentally a set of questions (multiple choice, matching, short-answer, numerical or essay) that are usually automatically assessed (except essays). Quizzes can be set with time limits, multiple attempts and various grading methods - all of these things are configurable. In addition, competencies can be set and evidence against them supplied.

Our issue in relation to quizzes in Moodle looks like "how much detail should we capture?" If we capture the assessment results at the level of individual question, then important information to give context for learning analytics becomes relevant, such as the question, answer, max grades, number of attempts, passing or completion grades.

There may be parameters for quizzes that could allow us to filter out the more pertinent quizzes or the more pertinent characteristics for learning analytics, or it may be possible (useful?) to collect everything relevant to the assessment. I'd welcome views on how we should approach this.

**Comment by arc12** [comment]
Some inclinations from me:
- statements for both questions and assessments
- include the min/max/etc
- follow well-beaten paths from the days of SCORM (for all this is a constrained world) and follow what already exists for the moodle plugin unless there is good reason
- probably keep the response and result in single statements, for lower statement volume and easier processing (this also feels a more natural way to deal with cases where we might have computer-marked and human-marked questions)

**Comment by alanepaull** [comment]
Naive question: "...the moodle plugin..."; where is this, and do I have access to what it contains, in terms of statements?

**Comment by alanepaull** [comment]
I propose up to 4 statement templates for handling quizzes, as follows:

question/quiz viewing
		Student could view a question or quiz without doing it; this would be very similar to vle_resource_viewed statement template.

question response
		The process of the student answering a quiz question. Should be a separate statement, optionally including Result (feedback and/or assessment) in the same statement for lower statement volume. This would be based on assignment-submitted.

question assessment
		The process of the student receiving feedback or result of assessment of quiz question after a time period (in other words, not covered by the response statement, but by a separate statement). This would be based on assignment-graded.

quiz result
		The process of the student receiving feedback or assessment of the result of a whole quiz. Again, based on assignment-graded.

Some important assumptions:

- Each quiz question has its own ID.
- Quiz will have a result. Could there be a quiz where questions have result, but overall quiz doesn't?
- Question results don't have to relate to quiz result in the LA data (though in practice they will probably do so); in other words, the LA system doesn't have to calculate the result of the quiz or even know how to do it. If we know that data, I guess it could be included, but would we want to?

I'm drawing up quiz templates shortly with examples.

**Comment by ds10** [comment]
Commit by @alanepaull for review: The feature-quiz branch contains a quiz_view.md in the recipes/vle directory and the vocab.md has been updated.

**Comment by alanepaull** [comment]
Draft quiz statement templates added to the Feature-quiz branch, with appropriate amendments to vocabulary. Question: Common structures - is it OK to reference the common structures, and indicate where changes have been made in the statement template? I don't think there is any need for the common structures file to include ALL the versions of the structures (else they're not "common").

**Comment by katie942** [comment]
hey!
thank you for the information
that was definitely informative
katie smith
[http://sortmyassignment.com/](http://sortmyassignment.com/)
