### ISSUE TITLE
xAPI recipes for library data

### ISSUE THREAD

**Issue by timstratton** [jiscdev/xapi#150]
Wanted by Abertay in particular.

**Comment by arc12** [comment]
@timstratton - would Abertay be able to provide some detail here:
- what scope of "library data": turnstile, lending, e-books, journals, reading list software...?
- outline of the data structures which they can extract from

**Comment by ds10** [comment]
The feature-library branch contains recipes that were started by @michaelwebbjisc, but we have not yet seen data structures are not in scope for 1.0 so are not currently being worked on.

These are the ones that have brought up before and have a statement template that needs to filling out:

- PC Logged On	
- Viewed Reading List	
- Viewed Reading List item	
- A person authorises a request	
- A service authorises a person to access an application.	
Visited Library

**Comment by pbailey64** [comment]
These were the requirements we prioritised with OCLC , although it was a longer list
•	Borrowing a item – information available i system included branch, item, time stamp, format, bar code, email address, author?? custom…discipline, …
•	Accessing e-Content/Search/Downloading/etc.
•	Reading lists for modules/link with a module
secondary
•	Login – Access different systems in library

**Comment by pbailey64** [comment]
Key challenge was "linking events to modules" hence the need for reading list.

**Comment by ds10** [comment]
Brill thanks. After going over the notes from the last team call. I am currently working on 'generic templates' that can be reused across different contexts. Some of the requirements fit these 'login and accssed'.

**Comment by pbailey64** [comment]
Agree - many of these can be covered with a generic template. So useful to see full list
•	Entering/leaving the library
•	Borrowing a book – branch, item, time stamp, format, bar code, email address, author?? custom…discipline, …
•	Accessing e-Content/Search/Downloading/etc.
•	Login – Access different systems
•	Reading lists for modules/link with a module
•	Asking a question to an information specialist/Leaving feedback
•	Attending information training/Accessing online training
•	Authorising access
•	Checking viewed
•	Setting targets
•	Making a request
•	Renew/hold/inter library
•	Time on a resource
•	Download article
•	Search database
•	Login into computers/access rooms/….
•	Paying fines etc.
•	Requesting access cards
•	Engaging with “games”/induction process
•	Engagement between students and librarians
•	When an event happens (e.g. Accessing a resource)
•	Google analytics – e.g. Worldcat discovery – Future for KB

**Comment by ds10** [comment]
I've pulled 1.0 into the library-feature branch so the generic templatesare in there. Using them I have made first 4 statement templates @pbailey64 has sugguested and linked from the readme. There are a  few more in the recipes/library directory from ealier discussions - but I am not sure how helpful they are.

I do not know library systems, so perhaps Lee, Paul, myself and Alan want a chat around these 4 and the examples as a starting poing

**Comment by ds10** [comment]
I think myself. @pbailey64 @leebaylis and @alanepaull could do with having a look at these basic library statements and seeing what extra is needed would be a good idea. Are people ok with this? Can I create a doodle poll for a skype call?

**Comment by timstratton** [comment]
Sounds good to me

**Comment by pbailey64** [comment]
David - yes would be useful.

**Comment by ds10** [comment]
https://doodle.com/poll/bkgk6p422hi45q6t I think anybody with an interest is welcome. I think @pbailey64  and @leebaylis have met the tech fold and If @alanepaull is free it would be good for both Cetis people to be there.

**Comment by ds10** [comment]
@leebaylis @pbailey64 @alanepaull 2-3pm on friday looks hopeful. If so is skype ok? I need Pauls details if that is ok. You can add me at dms2ect.

If you want to look at templates first they are in the library branch. The 4 main ones are linked from the readme, although there are some older ones that were worked on in the recipes. Having said that, you don't need to look before the call.

**Comment by pbailey64** [comment]
Ok - sent you an invite via skype p.bailey

**Comment by ds10** [comment]
Thanks for the call, we discussed the way forward is to concentrate on the econtent and borrowing because we have this data. Aiming for v1.0. 

TODO:
- Lee to get headings to David from OClC EZProxy and from Worldshare
- David/Lee to map this to the work David Has already done
- Lee to check this against XAPI translator
- Paul/Lee to enquire about Login Data

Todo later..
- Lee/Paul to explore login data
- Lee to cross reference library data with future sets
- Lee/Paul contact Talis

**Comment by leebaylis** [comment]
EZproxy log file:
client_ip 
username_if_obtained_from_identd (usually '-')
username_if_obtained_via_other_means 
session_id 
timestamp 
http_request 
http_response_code 
bytes_downloaded 
not sure -- 'Default' or '-'
http_referrer 
http_browser_info

**Comment by leebaylis** [comment]
Worldshare log file:
Event Branch Name				e.g. main library
Event Type						e.g. checkout, renewal
Event Date				
Event Day Name of Week			e.g. Tuesday
Event Due Date/Time				e.g. book return date 
Event Loan Policy					e.g. 21 day, short loan
Item Barcode						identifier
Item OCLC Number					identifier
Item Title							
Item Call Number					dewey number
Item Material Format				e.g. book, journal
Item Branch Name					see event branch name, e.g. main library
Item Permanent Shelving Location		string
Item Temporary Shelving Location		string
Item Renewal Count				integer
Event Borrower Category			e.g. UG, PG, staff, libstaff
Patron Barcode					identifier for borrower, x-ref udd
Event Staff Full Name				string name for librarian processing request
Patron Custom Category 1			custom, repeats of info from UDD
Patron Custom Category 2			custom, repeats of info from UDD
Patron Custom Category 3			custom, repeats of info from UDD
Patron Custom Category 4			custom, repeats of info from UDD

**Comment by leebaylis** [comment]
First stab at templates below. Notes:
- ezproxy was easier to do -- have I got the right idea using a 'resource' object definition type?
- not sure where to put the downloaded bytes in the ezp recipe -- the attachments structure seems overkill, so should we craft an extension for it? surprised one doesn't exist already...
- worldshare will need more custom URIs and I will ask at the meeting later which make sense to be jisc ones (across other providers too) and which make sense to go in an OCLC namespace. for now I have slung some example oclc uris in. 
- the main two I am still unsire about are the object definition type and the verb id

**Comment by ds10** [comment]
Thanks for the feedback - I think the things you are unsure about are the things I wanted to talk about because I wasn't sure either. These templates are moving out of 1.0 and in to the feature branch, I think that is for the best because it gives us time to think this through.

I think a catch up after you've spoken to the vendors and then opening this up to the rest of the group (once 1.0 is frozen?) might help us with these issues.

**Comment by leebaylis** [comment]
OCLC:
{
  "version": "1.0.0",
  "actor": {
    "objectType": "Agent",
    "account": {
      "name": "**UNAME**",
      "homePage": "**HOMEPAGE**"
    }
  },
  "timestamp":"**TIMESTAMP**",
  "verb": {
        "id": "http://id.tincanapi.com/verb/viewed",
        "display": {
            "en": "viewed"
        }
    },
  "result":{
      "completion": **COMPLETED**,
      "response": "**HTTP_RESPONSE**"
  },
  "object": {
      "objectType": "Activity",
      "id": "**HTTP_URL**",
      "definition": {
	  "type": "http://id.tincanapi.com/activitytype/resource",
	  "name": {
              "en": "eResource"
          },
      "description": {
        "en": "an eResource made available via a proxy service"
        }
      }
    },
    "context": {
        "platform": "UxAPI",
        "extensions": {
	    "http://xapi.jisc.ac.uk/sessionId": "**SESSION_ID**",
	    "http://id.tincanapi.com/extensions/ip-address": "**IP**",
	    "http://id.tincanapi.com/extension/referrer": "**HTTP_REFERRER**",
	    "http://id.tincanapi.com/extension/browser-info": "**HTTP_BROWSER_INFO**",
            "http://xapi.jisc.ac.uk/recipeVersion": "attendanceV0.1"
	    //bytes?
	}

    }

 }

**Comment by ds10** [comment]
@leebaylis  I'll update the repostiory example to look like this when I move it out of 1.0 back to feature-branch. recipeVersion is depreciated though as we have a version of the profile instead.

**Comment by leebaylis** [comment]
Worldshare example
{
  "version": "1.0.0",
  "actor": {
    "objectType": "Agent",
    "account": {
      "name": "**PATRON_BARCODE**", //udd lookup?
      "homePage": "**HOMEPAGE**"
    }
  },
  "timestamp":"**EVENT_DATE**",
  "verb": {
        "id": "**EVENT_URI**", //construct -- OCLC namespace? jisc namespace? or even inst namespace?
        "display": {
            "en": "**EVENT_TYPE**"
        }
    },
  "result":{
      "completion": true
  },
  "object": {
      "objectType": "Activity",
      "id": "**ITEM_BARCODE**", 
      "definition": {
	  "type": "http://id.tincanapi.com/activitytype/resource", //custom per material format?
	  "name": {
              "en": "**ITEM_MATERIAL_FORMAT**"
          },
      "description": {
        "en": "**ITEM_TITLE**"
        }
      },
      "extensions": {
	  "http://oclc.com/number": "**OCLC_NUMBER**",
	  "http://oclc.com/item_location": {
	      "http://id.tincanapi.com/extension/location": "**ITEM_BRANCH_NAME**",
	      "http://oclc.com/permanent_shelving": "**ITEM_PERMANENT_SHELVING_LOCATION**",
	      "http://oclc.com/temp_shelving": "**ITEM_TEMPORARY_SHELVING_LOCATION**"
	  },
	  "http://xapi.jisc.ac.uk/dewey_code": "**CALL_NUMBER**"
      }
    },
    "context": {
        "platform": "UxAPI",
        "extensions": {
	    "http://id.tincanapi.com/extension/location": "**EVENT_BRANCH_NAME**",
	    "http://oclc.com/loan_policy": "**EVENT_LOAN_POLICY**",
	    "http://oclc.com/due_date": "**EVENT_DUE_DATE**",
	    "http://oclc.com/librarian": "**EVENT_STAFF_FULL_NAME**",
	    "http://oclc.com/renewal": "**ITEM_RENEWAL_COUNT**",
            "http://xapi.jisc.ac.uk/recipeVersion": "attendanceV0.1"
	}

    }

 }

**Comment by ds10** [comment]
@leebaylis Update to borrowed after 20th July call. 

I've updated the borrowed statement to what we agreed, having gone through it again I think the most pressing bit of work will be working out the activityTypes in the statements/.

We spoke about how we submitted experimental data, we put x-ignore or x-[datastamp] in the context.version property. The statement template has it in the example.

I've left the some of the draft notes in and haven't filled in the vocab document because I feel this is still very much in draft! The actor and verb are common objects, so I have just put in tables of values for object and context. I have left out result.

I will do the same for econtent, but I think that is going to be easier.

**Comment by ds10** [comment]
I've brought the 4 statement templates we are working on for 1.0.1 into the 1.0.1 dev branch. I think we need another call @leebaylis for the following:

- We made good progress on borrowed and viewed - I've started to tidy them up and add definitions and templates. I think we need to see what these look like now youve had time with them - see what changes we propose and show them to the group.
- Reading list view and login are not fleshed out, I think I need to know if we have example datasets to flesh them out

**Comment by leebaylis** [comment]
OK, how are you fixed for Fri 5th Jan for a call in the afternoon (after 1330?)

**Comment by ds10** [comment]
Sounds fine, is 2pm ok?

Started on the inputs and template files - there is some discussion to be had at a monday call on the final structure of these, but you may want to cast an eye over them?

**Comment by leebaylis** [comment]
2 it is!

**Comment by ds10** [comment]
Update from latest call: 
* Only borrowed and access are 1.0.1 ready 0 others to return to feture branches
* This repo is now the place for all development
* David Mint something for bytes downloaded - it is context of the activity and not an attachment to the activity.
* David to check consistancy between files
* Both to check through templates and load sandbox with data
* object IDs still need looking at

**Comment by jesvyjoseph** [comment]
Hello all

Is there an update on the xAPI recipes for library data or any sample statements? Im trying to integrate data from OCLC Worldshare into a data warehouse and came across this thread. any leads would be much appreciated!

Thanks a lot!

**Comment by ds10** [comment]
Hi,

Library recipes that are to be included in the next release are in 1.0.1 branch, ones which have not yet been fleshed out with vendors are in the library feature branch.

Happy to talk on skype with you if you want showing around: skype is dms2ect

**Comment by ds10** [comment]
moved to #228 and #229
