### ISSUE TITLE
Voiding attendance events

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#156]
There are circumstances when the records of a timetabled event are suspect.
e.g. the room was changed because the heating was broken so half the students swiped into the correct room and half didn't.
Depending on the data flow, this might lead to statements being sent for non-attendance which are incorrect.

The recipe should indicate how this is to be handled. At UCS (now U of Suffolk) they set already-stored records to have a NULL for the attended flag. This allows the cancellation to simply propagate to data consumers.

The "classic" xAPI way is to use statements with a verb of voided.

Is that how we will do it?

**Comment by ds10** [comment]
As far as I am aware the usual way to do this is the way which you have described, send a statment of verb avoid. However, this require querying the store for the ID of the statement we wish to void? How possible is this in the current infrastructure?

I'll add this to weekly call tag..

**Comment by michaelwebbjisc** [comment]
https://www.ht2labs.com/blog/void-xapi-statement/

**Comment by ds10** [comment]
This was marked as an implementation issue rather than a xapi repository issue
