### ISSUE TITLE
Moodle and Blackboard object definition types in assessment statements

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#160]
As I've been going through the assessment materials, I've noticed that object definition types look a bit odd in the Moodle and Blackboard vle json files (1.0 and master).

**Blackboard assignment_submitted.json**
	Note: type = http://adlnet.gov/expapi/activities/module
	
```
"object":{
        "objectType":"Activity",
        "id":"https://jisc.blackboard.com/webapps/gradebook/do/instructor/enterGradeCenter?course_id=_47_1&cvid=fullGC#",
        "definition":{
>>>     "type":"http://adlnet.gov/expapi/activities/module",
            "name":{
                "en":"Course 47 Assignment"
            },
            "description":{
                "en":"Course 47 Assignment description"
            }
        },
```
        
**Moodle assignment_submitted.json**
	Note: type = http://adlnet.gov/expapi/activities/module

```
    "object": {
        "objectType": "Activity",
        "id": "http://localhost:8080/moodle/moodle/mod/assign/view.php?id=4",
        "definition": {
>>>     "type": "http://adlnet.gov/expapi/activities/module",
            "name": {
                "en": "Assignment 2"
            },
            "description": {
                "en": "<p>Assignment 2<br></p>"
            },
            "extensions": {
                "http://xapi.jisc.ac.uk/extensions/duedate": {
                    "duedate": "2016-04-14T00:00:00-07:00"
                }
            }
        }
    },
```
    
**vle_assignment_graded statement template**
	Note: type = http://adlnet.gov/expapi/activities/assessment

```
"object":{
	"objectType":"Activity",
	"id":"http://moodle.data.alpha.jisc.ac.uk/course/view.php?id=4",
	"definition":{
>>>		"type":"http://adlnet.gov/expapi/activities/assessment",
		"name":{
			"en":"Course Assignment"
		},
		"extensions":{
			"http://xapi.jisc.ac.uk/dueDate": "2016-02-05T17:59:45.000Z"
		}
	}
```
	
I realise that the design of the template permits the object to be any object in the common structures page. However, with the type definition for the object set as a module, how does the system pick up that this statement relates to an assignment not a module, other than perhaps through the vendor-specific id?

We may have a documentation error perhaps, because I would have expected the object in this statement to be an assessment type, not any object in the common structures page.

Or am I missing something?

**Comment by ds10** [comment]
From Mondays call:
Types needs to be changed in moodle and blackboard examples to assesment.

**Comment by ds10** [comment]
These examples are generated by the plugins. We've used outputs so we know exactly what is being outputted. So these need to be generated by @michaelwebbjisc or @MiroslavKratchounov by adding them or sending us the snippet.
