### ISSUE TITLE
Attendance: "http://xapi.jisc.ac.uk/courseArea": { in wrong place

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#165]
In the VLE recipe this is in context, but it's now in object for attendance.

It needs to be in the same place for both, so we should move it back to context for attendance.

**Comment by arc12** [comment]
should it be there at all? 
Semantics seem all wrong for attendance; the URI desc is "Umbrella course/parent area by its home page URI "

This seems to be a typo from cut/paste of text which came from VLE-land.

**Comment by michaelwebbjisc** [comment]
yes, we need course area.  It matches the lecture to a module instance.

**Comment by arc12** [comment]
There is clear logic in a vle setting, a concept which is the "course area". I cannot see this applies to attendance.

We do have the udd mod instance ID there in the recipe for attendance.

Is this the case where Michael wanted to include this vle_mod_id and immediately deprecate it, as an interim workaround? If so, all we need to do is to leave things be and document the deprecation... and not worry about it being in the right place.

**Comment by michaelwebbjisc** [comment]
No, it's not that, but I've noticed we've lost a value to.
It should be:

**Comment by arc12** [comment]
uddModInstanceID is there, as an extension in the object definition.
Its not within the courseArea structure

I think uddModInstanceID is fine.

**Comment by michaelwebbjisc** [comment]
Ok, missed that.  We need to move it back as we had it originally though, so we have a consistent place to look for joining courseArea info to the UDD - it's going to confuse everyone too much otherwise.

**Comment by arc12** [comment]
Can we have this as an item for the next call please.

**Comment by michaelwebbjisc** [comment]
Yes, that's fine.

**Comment by ds10** [comment]
From Mondays Call:
- We create a is timetabled event extension that is boolean.
- Move coursearea to context
- Move uddmodinstanceid to coursearea.
- Change text that describes coursearea in vocab
- Document how to use it in 4.2
- Update other statements and generic states that use coursearea

Wants to be broad enough so that it can link to the UDD (needs uddmodinstanceid) and needs id to identify to the section of VLE.

**Comment by ds10** [comment]
ToDo: timetabled event is now a boolean extension, lecture is now the examples object.def..type. Double check this and subtype after updating documentation

**Comment by ds10** [comment]
The following changes were made:

- Create a is timetabled event extension that is boolean.
- Move coursearea to context
- Move uddmodinstanceid to coursearea.

Would like to check I understand this correctly (#168) Before closing the issue
