### ISSUE TITLE
Context.ContextActivities vs Context.Extensions.CourseArea

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#168]
I might be missing something here, but we seem to have two properties doing similar things in the vle recipes. It

In the documentation most of the common structures can use CourseArea extension, which (I think) was originally used  to link to the UDD in the context. This does have an ID too, which I think Adam was using to using to find where resources lived.

ContextB however allows for a contextActivities property with a ‘grouping’, that allows an additional ObjectA statement in the context to be associated to the activity described in the statments object.

The only statement templates to use contextB are the assignment graded and assigned. Both these statements in the Moodle and Blackboard examples use the contextActivities, but it has also snuck into the [blackboard courseaccess example](https://github.com/jiscdev/xapi/blob/1.0/vle/blackboard/course_content_access.json), although if that is using the resource viewed template then it should be using contextA which doesn't allow contextActivities.

In both the Blackboard and Statement template the type in the ContextActivites object is courseArea while the moodle example uses http://xapi.jisc.ac.uk/define/vle/course.

Are these properties doing the same thing now? Or should ContextActivities groupings be an option property to more of the generic recipes with the blackboard course content access using it.

I'm not sure how the analysts are using it..

**Comment by ds10** [comment]
#165

**Comment by arc12** [comment]
One of the problems I think we identified was that contextActivities is framed as an open list, which we felt to be problematical from a practical point of view. This is, however, the "standard xAPI" way. I think we ended up with two ways of doing the same thing because we wanted to have the cake and the ha'penny:
- something standards-y so other people might be able to use the data who worked that way
- something we would actually use ourselves

OTOH, I might be thinking about something a little different to what you are querying, David...

**Comment by alanepaull** [comment]
I think that this is basically correct, in that the courseArea extension does the same job as the contextActivities grouping structure - it's for showing the wider context in various ways. However, it also links the UDD and vle module IDs, so I'm not (yet) sure if that works with contextActivities.
If it's possible to drop the courseArea extension and use courseArea in the contextActivities structure, I think that would be preferable (but I would say that, wouldn't I?). We'd need to check that it supports all the data we need there. And it there are technical issues, probably live with what we've got.

Also, we'll need to be careful about the meaning of the various contextActivities. We may / should apply them to some sections of our current design work, or we may be re-inventing some wheels. This refers: https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#context.

For example: "a Statement about a quiz question would have the quiz as its parent Activity." Note - NOT as its grouping Activity. So, most modules would have a Course as their Parent (and grouping wouldn't be appropriate).

**Comment by ds10** [comment]
From Monday call. Remove Context.ContextActivities from recipes as Context.Extensions.CourseArea duplicates this information

**Comment by ds10** [comment]
This changes the statements for assignment graded and assignment submitted from contextB common statement to ContextA as the only difference between the statements is the  addition of Context.ContextActivities... which we have just decided to remove. I will leave ContextB in the common statements with a deprecated tag for now

**Comment by ds10** [comment]
updated to remove context.contextactivities. Moodle and blackboard json examples need updating.
