### ISSUE TITLE
Remove Session-timeout.md

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#170]
Hi everyone,

We're going to have to retire this recipe:

https://github.com/jiscdev/xapi/blob/master/recipes/Session-timeout.md

It's Blackboard only, and not proving technically viable.  We'll be removing all data with this template from the LRW, as its not actually reflecting user activity, but more a function of how the system works.

Alan, can you mark this has depreciated for xAPI 1.0?

Going forward, we'll give some though on how we can get something equivalent of an 'end of session' element so we can start looking at time from user logging in to leaving, but it's not going to be that straightforward.

Michael

**Comment by alanepaull** [comment]
Hi Michael
We'll do that. We can confirm the issue on Monday's call.
Alan

**Comment by arc12** [comment]
+1
in practice, I think the only workable approach is to analyse events in terms of a combination of the interval between events and session id. The variety of approaches in software and of modalities in student use will always make this somewhat arbitrary and in need of hueristics.
