### ISSUE TITLE
Attendance: Lateness flag is string

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#174]
From @arc12 

The semantics are boolean. Example gives string. Documentation should be explicit about type (not just leave to example) and ideally be a JSON bool or integer 0/1 to match semantics

**Comment by ds10** [comment]
Explicit information stating the data type and value space was in the vocab, but the example in the template was wrong and there was no link from common statements to vocab, what I have done and proprose for all these similar issues:

1. Changed examples so they are correct.
2. Make sure that vocab, common statements and template all link to each other
3. Add addition data type/value space column to the common statements to make it clear.
