### ISSUE TITLE
Attendance: Mandatory flags type not explicit

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#175]
From @arc12 
Mandatory flags type not explicit
Example gives an integer. Needs explicit type in documentation. Should be consistent with lateness

**Comment by ds10** [comment]
This is similar to 173, the vocab document gives information on the type and value rang, in this case there was a link from the common structures to the vocab, but it was not clear or obvious.  I've added the additional information column to the common structures table, which was messy and unclear.
