### ISSUE TITLE
Attendance: Object.definition.type

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#177]
From @arc12 

Object.definition.type is given as “"http://xapi.jisc.ac.uk/lecture", which is inconsistent with the documentation of ObjectD (and with conference call decision)

**Comment by ds10** [comment]
I think I the documentation is out of sync for this and #178. The documentation for subtype in objectd says: Permitted values are: "http://xapi.jisc.ac.uk/lecture" or "http://id.tincanapi.com/activitytype/tutor-session". But this might be from when we were going through the motions of what subtype is. Can we get clafication on what the object.definition.type and apprioriate subtypes are?
