### ISSUE TITLE
Attendance: Check Examples

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#179]
From @arc12 
Check examples
e.g. the context example contains a spurious “id” in the courseArea, with a Moodle URL
Object.definition.extensions in the full example contains data types which differ from earlier component examples (max count and mandatory)

**Comment by ds10** [comment]
I am confused about the id in coursearea? courseArea in version 0.5 has an ID and vle_mod_id as in the example that comes from the [current plugin](https://github.com/jiscdev/xapi/blob/master/vle/moodle/asssignment_graded.json). The only change in 1.0 is that UDD Module instance is also included.

The documentation in the vocab page isn't great, it says properties of coursearea are an id, which is the URI identifier of the course, vle module id and udd module id.

I can update the documentation and make things clearer, but need to understand why id was used in 0.5 but is not spurious.

Will update the other examples which are out of date.

**Comment by alanepaull** [comment]
Monday 3 July. courseArea: agreed to remove the ID property from courseArea, so courseArea will contain only vle_mod_id and uddModInstanceID. Note: this applies to all instances of courseArea, so all relevant examples and templates will need to be updated. I'll be addressing that as I go through the templates. This will also mean amending vocabulary and common_structures.
