### ISSUE TITLE
attendance: datetime

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#181]
current attendance statment has planned start time and  end time?

The current statement uses a planned start time and end time (in objectD), I am sure at one stage we decided on datetime and duration instead. ObjectC has planned datetime and duration but no recipes use this object structure at the moment. My guess is that ObjectC was in the old event statement which was put forward by Cetis september of last year, but has  been replaced by the current one at some point.

Q) Should attendance have datetime and duration rather than start and end times?

**Comment by arc12** [comment]
we did discuss start/end vs start/duration.
I think the conclusion was to use start/end because that avoided the question "what units of time for duration"

**Comment by ds10** [comment]
Discussed that this was correct at 3/7/17 call
