### ISSUE TITLE
Verb 'scored' in assignment-graded

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#184]
Current text defining the Verb is "The Verb, [scored](/vocabulary.md#verbs) describes the action of evaluating a learning activity."

This looks incorrect to me, because we use this to indicate that the student has received a score. The student isn't doing the evaluating. I propose to change this to:

"The Verb, [scored](/vocabulary.md#verbs) describes the student receiving a score for a learning activity."

And to add to the Purpose section:
"Natural language example of a typical statement: "John Smith scored 90% for his ABC assignment in module LA101 (raw score 88%), marked by Angela Jones, indicating successful completion."

**Comment by arc12** [comment]
"raw score 88%" ?
Agree with the semantic quibble. ADL vocab notes: "Indicates a numerical value related to an actor's performance on an activity."

I would have taken a raw score to be an unscaled one. e.g. 45 (with min 0 and max 50)

"successful completion"?
xAPI core doc differentiates success and completion, so it may lead to confusion to combine them.

**Comment by alanepaull** [comment]
This better?
"Natural language example of a typical statement: "John Smith scored 90% when he completed his ABC assignment in module LA101 (raw score 45), marked by Angela Jones, indicating success on this assignment. Minimum possible score: 0; maximum score: 50."

**Comment by alanepaull** [comment]
I've implemented these changes to assignment-graded:

Definition changed to - "The Verb, scored describes the student receiving a score for a learning activity."

Purpose, added sentence - "Natural language example of a typical statement: "John Smith scored 90% when he completed his ABC assignment in module LA101 (raw score 45), marked by Angela Jones, indicating success on this assignment. Minimum possible score: 0; maximum score: 50."

Context, added table indicating content. Changed to relate to ContextC in common structures (was ContextA, which was not correct, as had no reference to Instructor). In this template, I've deleted deviceLocation, as it doesn't seem relevant and is not in the Moodle example. So Context is:

<table>
<tr><th>Property [cardinality]</th><th>Description</th><th>Value information</</th></tr>
<tr>
	<td>context.instructor [0..1]</td>
	<td></td>
	<td>JSON Object</td>
</tr>
<tr>
	<td>context.instructor.objectType [1]</td>
	<td>Must be "Agent"</td>
	<td>String, Must be "Agent"</td>
</tr>
<tr>
	<td>context.instructor.account.homepage [1] </td>
	<td>URL of the home page of the application for which the login id applies.</td>
	<td>url</td>
</tr>
<tr>
	<td>context.instructor.account.name [1] </td>
	<td>account.name gives the login id for the instructor.</td>
	<td>string</td>
</tr>
<tr>
	<td>context.extensions.version [0..1]</td>
	<td>Recommended,  identifies the version of the Jisc xAPI profile found on the ReadMe page.</td>
	<td>string</td>
</tr>
<tr>
	<td><a href="vocabulary.md#course-area">context.extensions.https://xapi.jisc.ac.uk/courseArea</a> [0..1]</td>
	<td>Umbrella course/parent area by its home page URI and / or its identifier.</td>
	<td>JSON object</td>
</tr>
</table>

And Example is:

``` javascript
"context": {
		
	"instructor": {
            "objectType": "Agent",
            "name": "Ray Keenan",
            "account": {
                "name": "RKeenan",
                "homePage": "http://localhost/moodle"
            },
        
    "platform": "Moodle"
	
    "extensions":  {
      	"http://xapi.jisc.ac.uk/courseArea": {
			"http://xapi.jisc.ac.uk/vle_mod_id": "LA101",
			"http://xapi.jisc.ac.uk/uddModInstanceID": "LA101-200-2016S1-0"
              	},
				
		"http://xapi.jisc.ac.uk/sessionId": "32456891" ,
		"http://id.tincanapi.com/extension/ip-address": "10.3.3.48"
		"http://xapi.jisc.ac.uk/version" : "1.0"
        }
```

Note that courseArea only has vle_mod_id and uddModInstanceID now.

Moodle and Blackboard specific examples will need to be changed, as they both have contextActivities.grouping, which is not appropriate for this template in v1.0.

Additional note: the template includes this - "In the Jisc profile, the use of the result entity and any of its properties is optional." I don't think that this is appropriate for assignment-graded, so I propose to remove it; in fact Result should be compulsory in this template, I think. Any objections/comments?

**Comment by alanepaull** [comment]
Changes completed.
