### ISSUE TITLE
Attendance: verb definition

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#186]
Currently: 

Verb
Common entity identifier: VerbA
Entity Example:
The verb attended denotes the action of the user's browser or app requesting the resource that the user wishes to view.
``` javascript
"verb": {
        "id": "http://adlnet.gov/expapi/verbs/attended",
        "display": {
            "en": "attended"
        }
    },
```
Should be (I think) as follows, with the definition as given in the "attended" verb definition from ADL:

Verb
The verb used in the attendance statement is **attended** (http://adlnet.gov/expapi/verbs/attended). It indicates the actor was present at a virtual or physical event or activity. It uses the Jisc common entity identifier VerbA.

Entity Example:
[just the example above]

**Comment by arc12** [comment]
agreed. 
documentation bug!

**Comment by alanepaull** [comment]
Now revised as above and committed.
