### ISSUE TITLE
VLE Forum vs tincanapi discussion

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#189]
Currently in the vocabulary.md we have VLE Forum as http://xapi.jisc.ac.uk/vle/forum. However, there is an existing tincan object called http://id.tincanapi.com/activitytype/discussion. Is there any objection to using this existing type, rather than minting our own? It is already being used as a forum object elsewhere.

Alan

**Comment by arc12** [comment]
vle/forum is already being used for VLE read statements

**Comment by alanepaull** [comment]
Just noting here that it doesn't appear to be in any of our current statement templates in v1.0. Which may or may not be relevant.

@arc12: how big an issue is that?

**Comment by arc12** [comment]
it is in the vle verb="viewed" scope.

**Comment by alanepaull** [comment]
I should have said: not in our approved statement templates; it's in our very drafty forum ones. Would it be possible, preferably easy, to modify existing stuff?

I'm conscious there may not be appetite to do this type of thing, but on the other hand, using established  terminology is preferable to not.

**Comment by arc12** [comment]
@alanepaull - we've been using forum view statements as one of the object.definition.types for https://github.com/jiscdev/xapi/blob/1.0/recipes/vle/Module-View.md

There are statements in the LRW
