### ISSUE TITLE
Attendance recipe does not mention xAPI timestamp (and should!)

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#195]
xAPI core spec includes timestamp as a core statment property. This is optional but xAPI core spec says "If not provided, LRS should set this to the value of "stored" time."

I suspect we DO want to have timestamp set, and in a meaningful way, as this is a key piece of information and there is considerable advantage to being able to query for statements of any kind using timestamp (i.e. we should have timestamp always present and intuitive).

xAPI spec also says "Where the experience occurs over a period of time, the timestamp can represent the start, end or any point of time during the experience. It is expected that communities of practice will define an appropriate point to record the timestamp for different experiences."

I suggest we document that timestamp for attendance is identical to the timetabled start time, and is required for the recipe. I don't think we should remove the start time property, though

**Comment by ds10** [comment]
attendance statement template now has a timestamp section stating this should be the same as starttime in 1.0.1
