### ISSUE TITLE
IRI for start/end time inconsistency

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#197]
The table and example for attendance uses starttime and endtime
https://github.com/jiscdev/xapi/blob/1.0/recipes/attendance/attendance.md

The vocabularies page uses planned-end-time and planned-start-time
https://github.com/jiscdev/xapi/blob/1.0/vocabulary.md#timetabled-event

**Comment by ds10** [comment]
The examples are correct and the vocab has missed an update? I'll double check the changes doc.

**Comment by ds10** [comment]
Looks like the vocab was out of sync, updated it to reflect the statement template. Since the examples where correct I've added this to 1.0 before the release, but will tag it for the next call
