### ISSUE TITLE
Assignment Graded documentation  for "result" should be tightened up

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#200]
The current documentation leaves too much open, and allows low quality data to be produced which is still compliant.

For example (taken from real customer data seen from Bb plugin):
>         "result": {
>             "score": {
>                 "scaled": 0,
>                 "raw": 34,
>                 "min": 0,
>                 "max": 0
>             },
>             "completion": true,
>             "extensions": {
>                 "http://xapi&46;jisc&46;ac&46;uk/grade": "34"
>             }
>         },

In order:
- the data is not scaled, so there should be no "scaled". It very definitely should NOT be zero
- the min and max are not known so these should not be given and definittely NOT be zero
- there is no grade (a "non-numerical assessment result") so this should not be given.

Providing all of these with a spurious value when there is actually no value just hurts meaningful data processing. This example is logically INVALID and I think the recipe should be clear so that the example is also clearly non-conformant; at present, it is arguably non-conformant against the spec but the lazy devloper still has a case for reasonable doubt.

Implications for spec - https://github.com/jiscdev/xapi/blob/1.0/recipes/vle/assignment-graded.md#result : be clear about including optional components only if there is meaningful data

Implications for plugin: get this fixed so the data is meaningful

**Comment by arc12** [comment]
Further: I think we should require at least one of the raw score or grade to be present for a valid statement, and if a numerical score is known then it must appear in raw score.

The implication of this is that where there is marking as a percentage (the marking is "scaled" from the outset) then we MAY get a value for scaled, but we would ALWAYS get a raw mark.

**Comment by arc12** [comment]
I've also just seen data with a raw score of 0 but a grade of 63%

!

I suppose I shouldnt be surprised that there is a developer out there who thought 0 was a sensible default for an unknown numerical score, or that there was such lax QA that this got into production code.

**Comment by ds10** [comment]
just to double check this is a 1.0.1 change because it doesn't actually need a change to the plugins for developers to follow new documentation? 

You have said this has an effect on plugins as they can be fixed to make sure it doesn't let anything past that isn't meaningful -but since at its core this is a 'sensible documentation for sensible developers' issue then it is 1.0.1? As the plugin change is just for additional validation, not change in spec

**Comment by ds10** [comment]
I've added some notes for developers in 1.0.1 explaining what scaled is, that unknown values shouldn't be 0 etc, but I am wondering if some of this is plugin issues - are the plugins putting properties as 0 if they are not known?

**Comment by alanepaull** [comment]
result.completion is currently optional, and it can have values of "true" or "false". I think that the meaning of assignment graded is that the assessment, or at least this assessment attempt, has been completed; unless there are specific cases where this is an interim result for this attempt that might be changed?
I'm suggesting that result.completion should be mandatory and set to "true". Please correct me if this assumption is wrong.

**Comment by alanepaull** [comment]
As result.success is optional and deprecated in Assignment Graded, I suggest that we don't include it in the vle-assignment-graded-template.json file in UxAPI v1.0.1.

**Comment by ds10** [comment]
Leaving as is - not causing a problem and  there may be edge cases.
