### ISSUE TITLE
problems with assignment submitted result

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#201]
https://github.com/jiscdev/xapi/blob/1.0/recipes/vle/assignment-submitted.md

typos/cut-paste error:
"result.completion [1] | When set to "true", result.completion indicates that the learner  attended the event; "false" indicates that the learner did not attend  the event."

It is also not clear what the result adds here. The verb is already "completed". If submission is considered to be completion (questionable IMO) then this is redundant. Logically, completion should be the final submission, in the case when multiple submissions are allowed, but this is only known retrospectively so we couldnt add it anyway...

**Comment by ds10** [comment]
This has been removed from 1.1, with a note in 1.0.1
