### ISSUE TITLE
assignment graded success is too vague

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#202]
https://github.com/jiscdev/xapi/blob/1.0/recipes/vle/assignment-graded.md

"result.success [0..1] | Indicates whether or not the attempt was successful"

The description lacks sufficient detail to have much confidence of consistent interprettion. If we mean pass/fail then we should say so... or meets minimum requirements (de facto the same IMO).

I have some doubt that the data to complete this is reliably identifiable in the original source data.

**Comment by ds10** [comment]
result.success as described in the xapi spec is: "Indicates whether or not the attempt **on the activity** was successful. " I read that as meets minimum requirments.

**Comment by ds10** [comment]
In my notes contradict themselves here. I have "For 1.0.1 update the documentation to say it will be removed in 1.1, Later we will decide what to do with it in 1.1"!

I've updated the documentation in 1.0.1 to state its removal in 1.0 and removed it from 1.1
