### ISSUE TITLE
assignment submission sequence number

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#203]
problem at the moment is that it is possible to have multiple statements referring to the same assessment (etc). These could be spread several weeks apart and it is rather inefficient to have to do the book-keeping required to reconstruct the submission count, especially when dealing with historical "training" data.

The cleanest would be for the VLE to supply this and for the statement template to accommodate a counter.

NB: I do not mean multiple *attempts* each with a graded outcome.

**Comment by ds10** [comment]
we decided to add a sequenceNumber but didn't go in to detail on the last call. In 1.1 branch I've added http://xapi.jisc.ac.uk/sequenceNumber to the vocab, contextA and assignment submitted recipe. The idea being that it can be used as a counter for any statement where the activity might be part of a sequence.
