### ISSUE TITLE
Create uXAPI-type entries for each xAPI statement template

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#211]
originally on UDD: 

UXAPI translator takes a tab seperate file, and matches it against a JSON file, in order to create xAPI output. This were documented as part of UXAPI, we agreed this week that this would be more widely useful, so CETIS could take this on and incorporate it into the spec.

Here is an example for attendance:

The Tab Seperated Input File (with format borrowed from UDD:

https://github.com/jiscdev/universal-xapi-translator/blob/master/attendance-input.md

A JSON template, show where in the statement template each field goes:

https://github.com/jiscdev/universal-xapi-translator/blob/master/attendance-template.json

In these, we use and internal Jisc notation:

**FIELD_NAME**

but we can change that as its a pain to write in MarkDown (two stars being the code for bold)

**Comment by arc12** [comment]
I think some conventions would be useful, but I'm not yet sure what they should be.

I note that we have some things which are intended to be "as in UDD". The example here uses the same names as UDD, although this means they differ from the names in the JSON. I think this is a good idea. How about that as a convention for naming. I suggest we need a counterpart convention in the documentation which indicates the relavant part of the statement template (etc) documentation, while also clarifying that the semantics are UDD-defined, and the template shows contextual application.

For the other cases, one convention would be to use a column heading which does reflect the xAPI JSON. For example, where there is an extension URI, to use the last part of the path. This doesnt work well for result.completion, which is not clearly about "did the student attend?" In general, though, I suggest a preference for using a column name which matches, so long as this makes things more clear, not less. i.e. avoid arbitrary deviation. In this case, we should be clear that the semantics are defined in the xapi recipes as well as the usage. This is probably obvious if the "tabular binding" (for want of a better name) is part of the xapi recipes repo.

I do favour it (the tabular binding spec) being done in a way which is quick and easy for busy institutional tech folk to work with; I think there is a lot of merit in doing it an a way which doesnt require the user to consult the main spec (and to get to grips with some of the ways the spec is structured, which make perfect sense from the POV of spec development but which are an impediment to newcomers). I think we could trim it down even from https://github.com/jiscdev/universal-xapi-translator/blob/master/attendance-input.md. For example the notes for the start date time could be one line to say what it is, one line to indicate for format, and a reference to the relevant section  of the statement template

**Comment by ds10** [comment]
Before I get to far in to this, I would like to chat about it at the next call so that we are sure about what we want before  we have a go at creating each entry. Other question, I have - in instances where we don't have need a tsv (moodle plugins), do we still want TSV definitions & JSON Templates. Perhaps for instances when they are using an VLE without a plugin?
