### ISSUE TITLE
Actor.name - include or not?

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#212]
In various examples and templates we have specs for Actor, meaning student, that may or may not include the student's name. This is Actor.name (not Actor.account.name). It's been talked over in various issues in the xAPI tracker, and the official situation at present seems to be that it's either real.name (full name?) or omitted (see #67). Main spec has this as "Full name of user", but [0..1].

However, if the definitive name comes from the UDD ( student FIRST_NAME + LAST_NAME), we shouldn't have it in the xAPI. Same for instructor.

I propose that we simplify by dropping Actor.name from the specs (MD files, TSV and JSON in the UxAPI) for the next breaking version (v1.1) and deprecate for v1.0.1. Then at least the specs will match most of the implementations.

**Comment by arc12** [comment]
We'd be happy with that. People may wish to include it, as per the xAPI core spec, but not including it in the Jisc templates doesnt stop that.

**Comment by ds10** [comment]
From weekly call: Remove actor name from specs
