### ISSUE TITLE
devicelocation/geojson inconsistency

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#216]
Looking at the attendance statement template, it uses a jisc IRI for the extension but
on the vocabulary page the IRI given is a geojson one.

Check for consistency across the repo.

**Comment by ds10** [comment]
I think we opted for a jisc  minted deviceLocation. I'll update vocab and check repo. see #158 and [commit](https://github.com/jiscdev/xapi/commit/ce41c38011ad38d9145e0031e6345b27246e904a)
