### ISSUE TITLE
Requirements for TSV definition files

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#219]
In the tsv files we have:

- Description
- Purpose
- Derivation,
- Valid Values
- Format

and adam has added
- Notes

Are all these useful and can the documentation be maintained? Some thoughts:

Purpose for most of these says 'analytics' in most instances. If we are keeping purpose then I would think it needs to be maintained by an analyst. Is it useful?

Is derivation useful? 

Perhaps with notes where required, derivation and purposes can be dropped?

Valid values and format are duplicated elsewhere in the documentation- they are in the statement template (or common structures) . Duplication is bad - but I still think there is scope for them here as the TSV inputs are a single thing to point instutions to when describing the data required. Any thoughts?

**Comment by arc12** [comment]
duplication is generally to be avoided, I agree, but so is assuming that readers go elsewhere to find important facts. In this case, the duplication is fairly easy to check, so low-risk.

I think that the TSV doc should generally provide enough info for someone to extract the data, or make explicit outbound references where the amount of info required is more than a few sentences. Conversely, info which is not of use to someone writing some extract SQL is probably something to delete.

**Comment by ds10** [comment]
Sugguest I remove purpose and derivation, but leave valid values and format

**Comment by ds10** [comment]
Weekly: decided to go with these conventions for each each statement template in 1.0.1

See tickets #219 #220 #215
