### ISSUE TITLE
Order of items in TSV definitions

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#220]
@arc12  has made changes to the order of items in the attendance tsv definitions

I gather this is for consistentcy in the documentation as statement templates go in an order of actor-verb-object. Just checking that this is the case, and if this makes life easier for the analysts then that this is the convention going forward

**Comment by arc** [comment]
Hi, I think you've got the wrong person :-)

**Comment by arc12** [comment]
Yes, this was so that the documentation for the TSVs ran in the same order as the doc of the xAPI statement template. It certainly made it easier for me to make edits to the TSV which were (I hope!) consistent with the xAPI.

**Comment by ds10** [comment]
OK - I sugguest that this is done for each template collection.
