### ISSUE TITLE
logic in translator

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#221]
I am not sure how the translator works so this might not even be an issue.

We've created JSON templates and TSV definitions for all statement templates. For the VLE templaets this is since the plugins might not always be generating the data. There must be some logic in the plugins beyond just inserting IRI's into the correct places.

I'm looking at the JSON template for resource viewed. Some resources in the object have subtypes and some  may not. I'm guessing that in the plugins this just a case of 'if $subtype exists then put it in else do not' type thing. Is the TSV to JSON translator able to cope with this kind of thing?

**Comment by ds10** [comment]
Another example - the current form approach uses 2 verbs depending on if it is created or replied to.

**Comment by michaelwebbjisc** [comment]
For the first example,, if there's no subtype in the input then the translator will exclude it from the xapi.

For the second, the actual verb needs to be in the input.

**Comment by ds10** [comment]
Just to check for the second:

For forum usage institutions aren't going to want to supply two lots of data 'create' and 'reply' for two converter jobs, just 'forum data'. So the statement template should be reworked to use the same verb and indicate elsewhere in the statement if it is a first post or not. -The forum statement is new to 1.0.1 so this isn't breaking anything.

**Comment by ds10** [comment]
Weekly: decided to go with these conventions for each each statement template in 1.0.1

See tickets #219 #220 #215

**Comment by ds10** [comment]
This is possible by having two input tsvs - instead it has been decided to have 1 and use subtype to decide if it is post or reply
