### ISSUE TITLE
Can we add a sample TSV files for each of the recipes

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#224]
This would make it easier for people to see what a valid input file looked like.  I'm creating some at the moment for Jisc that might be a good starting point.

**Comment by ds10** [comment]
This is no problem, but Im thinking we need 'real looking' synthetic data. Are the jisc ones a good starting point for cetis to create them.

**Comment by ds10** [comment]
actually thinking about it, all the new tsv defs and json templates need testing. We (cetis) can use the sample tsvs to test these. Doing both these tasks at the same time seems to make sense. We can talk about this at the call.

**Comment by gmoger-jisc** [comment]
Just to add an update, attendance example as been supplied and more will be worked on in due time.

**Comment by ds10** [comment]
Weekly call: After notes all recipes are ready - David to work with Gareth in getting new TSVs for them all that have been tested

**Comment by ds10** [comment]
@gmoger-jisc just to update you reguarding the weekly call. Alan and I are going to finish off the new statement templates and check the json templates,  1.0.1 would be ready but needs testing and TSV files. Can I check in with you soonish to work out a way forward on this?

**Comment by gmoger-jisc** [comment]
@ds10 can you give me some timelines is terms of when you need this?

**Comment by gmoger-jisc** [comment]
Sent via email to @ds10 for review

**Comment by ds10** [comment]
Does the tracking app statement need a TSV/json template/tsv definitions? I'm guessing that institutions won't be providing this?

**Comment by gmoger-jisc** [comment]
I would say not at this stage, no.
