### ISSUE TITLE
library borrowed template

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#225]
Hi,

note sure if I'm looking at the wrong branch, but in https://github.com/jiscdev/xapi/blob/1.0.1/recipes/universal-xapi-translator/library-item-borrowed-template.json  there are a lot of errors in the json template.

I won't list them all, but the main ones are the fields don't match, its not valid xapi (ie extensions extended object) and  the uid parts (eg **HOMEPAGE**/event/ were missing.

Just so it's recorded, here's one that produced valid xapi, with one extra field:

"http://xapi.jisc.ac.uk/statementCat": "**STATEMENT_CAT**" to make querying easier.

STATEMENT_CAT is actually library, so it doesn't really need to be a lookup.

```
{
    "version": "1.0.0",
    "actor": {
        "objectType": "Agent",
        "account": {
            "name": "**USER_ID**",
            "homePage": "**HOMEPAGE**"
        }
    },
	"verb": {
        "id": "http://activitystrea.ms/schema/1.0/borrowed",
        "display": {
            "en": "borrowed"
        }
    },
	"object": {
		"objectType": "Activity",
		"id": "**HOMEPAGE**/library/**ITEM_ID**",
		"definition": {
          "type": "**HOMEPAGE**/library/**ITEM_TYPE**",
          "name": {
            "en": "**ITEM_NAME**"
          },
          "extensions": {
            "http://oclc.com/number": "**OCLC_NUMBER**",
            "http://xapi.jisc.ac.uk/dewey_code": "**CALL_NUMBER**",
            "http://xapi.jisc.ac.uk/item_location": {
              "http://id.tincanapi.com/extension/location": "**BRANCH_NAME**",
              "http://xapi.jisc.ac.uk/permanent_shelving": "**PERMANENT_SHELVING_LOCATION**",
              "http://xapi.jisc.ac.uk": "**TEMPORARY_SHELVING_LOCATION**"
            }
          }
        }
	},
	"timestamp": "**TIMESTAMP**",
	"context": {

		"extensions": {
          "http://xapi.jisc.ac.uk/statementCat": "**STATEMENT_CAT**",
          "http://xapi.jisc.ac.uk/library_borrower_category": "**BORROWER_CAT**",
          "http://xapi.jisc.ac.uk/library_loan_policy": "**LOAN_POLICY**",
          "http://xapi.jisc.ac.uk/library_branch": "**BRANCH**",
          "http://xapi.jisc.ac.uk/library_renew_count": **RENEWAL_COUNT**,
          "http://xapi.jisc.ac.uk/version": "1.0.1"
        }

  }
}
```

**Comment by ds10** [comment]
OK, I think this is because it has gone back and forth in development and not been tested yet. I've fixed the template and I will double check the other library one - although Lee was still looking at the object identifiers for them still.

The main issue seems to be dodgy commas. I'll check all the ones that haven't been tested yet starting with library.

Question reguarding Statement cat: is this to be applied across all recipes and are the valid values "library", "vle", "app"

**Comment by ds10** [comment]
and "attendance" ?

**Comment by ds10** [comment]
We think this is to be rolled out to all recipe statements - use valid values as above for now

**Comment by ds10** [comment]
Added Statementcat to documentatiom - in vocab, common strucutres, md descriptions. Hardcoded in templates.

Valid values are "Attendance", "VLE", "Library"
