### ISSUE TITLE
library borrowed for 1.0.1

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#228]
1.0.1 Library borrowed TSV to include:

    USER_ID [1]
    ITEM_ID [1]
    ITEM_TYPE [1]
    ITEM_NAME [1]
    Timestamp [1]
    OCLC_NUMBER [0..1]

This removes everything else, makes OCLC [0..1] and Timestamp [1]

**Comment by ds10** [comment]
These have been cut back to the required, except for OCLC which is 0..1.

One question, my notes have "hardcode resource as itemtype and use subtype. To check I follow is this the kind of thing:

``` javascript
"object": {
	"objectType": "Activity",
	"id": "http://library.universityofjisc.ac.uk/0123456789" 	
	"definition": {
		"type": "http://xapi.jisc.ac.uk/library/resource",	
		"name": { "en": "Intro to Java" },			   
	 }
	
	"extensions": {
		"http://xapi.jisc.ac.uk/subType":"http://id.tincanapi.com/activitytype/book",
		"http://oclc.com/number": "OCLC_NUMBER",
			
		}
}
```

Do we have a list of subtypes?

**Comment by leebaylis** [comment]
Hi David, 
Yes, I think the tincan verb is correct for item type resource, and then subtype. 

We don't have a definitive list of subtypes -- I can propose one!
