### ISSUE TITLE
VLE Forum verb change

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#232]
- Verb is to be changed from a choice of two to posted. 
- Double check how we are using context activities. If we are allowing arrays of one then use this to point to previous post

**Comment by ds10** [comment]
Previous in VLE forum recipe we had two routes

1. verb:  "id": "http://activitystrea.ms/schema/1.0/create" type:  http://id.tincanapi.com/activitytype/forum-topic"

or

2. verb: "http://id.tincanapi.com/verb/replied"   "type": "http://id.tincanapi.com/activitytype/forum-reply"

My notes say to head towards a verb that is along the lines of 'posted'. Looking at the xapi registory, CLRecipes I've gone down the route of 'creating a post' etc.  I can't find any examples of a 'VLE forum post'  object type - the registory has forum-topic and forum-reply and general practice seems to be the way we mocked up the statement template.

For next weeks call to discuss I've minted xapi.jisc.ac.uk/vle/post which is any forum topic creation or reply. If it is a child to another post this will be indicated elsewhere in the statement.

* verb: "http://activitystrea.ms/schema/1.0/create" type: "http://xapi.jisc.ac.uk/vle/post"

It feels like I've missed something obvious or something we have previously discussed.

**Comment by ds10** [comment]
Other notes: the template use context.contextactivites to track the parent id - Im checking we decided this is ok because we are allowing arrays of 1. Rather than having grouping with all the posts (which would be an array)

**Comment by arc12** [comment]
I'm inclined to treat the object as a forum-post generically, i.e not to consider a vle forum post differently.

We have the platform anyway, as a means of narrowing down where the posting occurred.

**Comment by ds10** [comment]
In the template and forum example we have a context.extensions.http://jisc.ac.uk/forumArea . This hasn't made its way to the vocab yet.

I'm guessing this is a vle thing I'm not sure about, that forum posts can be in forumAreas - rather than something that was used to point to the parent post.

**Comment by ds10** [comment]
Found the ForumArea on ticket #132, which did contain the parent forum.  Changes for discussion:

- 1 verb and object: Create erb: "http://activitystrea.ms/schema/1.0/create" type: "http://xapi.jisc.ac.uk/forum-post" 
- ForumArea removed to use contextActivities in line with other statementtemplates. ContextActivities parent to be array of 1
