### ISSUE TITLE
"Platform" is not in the TSV file

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#237]
"Platform" seems to be missing from the TSV file for library-viewed-econtent. It's been entered in both the spec and JSON files as "UxAPI", as if it's a constant, but I believe this should be a variable for PLATFORM. 

So, TSV should have (I think):

### Description
The platform used in the experience of this learning activity. The value used should not change between platform upgrades and version changes and should typically be a concise name by which the application is commonly known, for example "Moodle" or "Blackboard".

### Valid Values
Any

### Format
String (256)

and the JSON should have:
```
"platform": "**PLATFORM**",
````

Can we confirm this please?

**Comment by ds10** [comment]
Platform has to be the platform used to experiance the learning activity, so I think that it should be included in the TSV.

Some of the original templates has UXAPI set as the platform, I'm not sure if it was in the original repository or in examples posted in tickets - but this doesn't seem right as UxAPI is the platform that has generated the statement and not where the learning activity takes place.

Ticket #222 has an example that Micheal has generated with 'attendance' as the platform.

Propose platform is supplied in TSV and that it is the platform the learner experiances the learning activty in

**Comment by arc12** [comment]
I concur that "platform" should refer to the source system.

I would also strongly prefer to avoid generic values such as "Attendance" since that goes against xAPI spec semantics. From a practical POV, this is a useful way of discriminating between the platforms and implementing differentiated data processing, which we'd need to reinvent somewhere else...

**Comment by ds10** [comment]
"attendance" being in platform: We've minted a context extension StatementCat that groups types of statements together for Jisc analysis anyway.

UxAPI being in platform: Do Jisc need to know if the statement was generated by a plugin or UxAPI?

**Comment by ds10** [comment]
Weekly call: context.platform, should be from source system, but doesnt need to be supplied in TSV defifinition,  but still in json template

**Comment by ds10** [comment]
JSON templates now require a **PLATFORM** but it is not in the TSV definition since it is supllied elsewhere
