### ISSUE TITLE
Library borrow item name mandatory on tsv version but not main listing

### ISSUE THREAD

**Issue by michaelwebbjisc** [jiscdev/xapi#239]
Customer spotted this one:

https://github.com/jiscdev/xapi/blob/1.0.1/recipes/library/library-item-borrowing.md

and

https://github.com/jiscdev/xapi/blob/1.0.1/recipes/library/uxapi/library-item-borrowed-input.md

I think 'ITEM_NAME' should be [0..1] on both.

**Comment by ds10** [comment]
Item name does appear to be on both, could be that we fixed this last week.

Is this the issue that was picked up and fixed by @alanepaull here: https://github.com/jiscdev/xapi/issues/236 ?

**Comment by ds10** [comment]
actually, just realised its 1 on the TSV descriptions..
