### ISSUE TITLE
No obvious key for the [0..1] entries against fields

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/xapi#240]
raised by Southwales: We have been telling them to look for optional fields, but they didn't recognise that the [0..1] syntax meant that the fields were optional. Can we make it clearer or supply a key or hyperlink the [0..1] sections to a nomenclature guide?

**Comment by alanepaull** [comment]
Clarification added to common structures file: https://github.com/jiscdev/xapi/blob/1.0.1/common_structures.md
