### ISSUE TITLE
TBC still present in eResource session_id field

### ISSUE THREAD

**Issue by leebaylis** [jiscdev/xapi#242]
raised by southwales: see https://github.com/jiscdev/xapi/blob/1.0.1/recipes/library/uxapi/library-viewed-econtent-input.md#session_id , still down as tbc.

**Comment by alanepaull** [comment]
Added to description:

"The local version of an identifier for the VLE session currently in use by the actor. A value should be provided if this information is available."

The format and content of this will be dependent on the VLE being used. Do we have a reasonably live example that we can use?

**Comment by ds10** [comment]
Weekly call: something like "If the system has a data item called session id"
