### ISSUE TITLE
Library recipe - OCLC_NUMBER

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#250]
Can we have more detail on the fields for the Library Borrowed recipe?  The OCLC_NUMBER specifically seems to cause some confusion (with myself too!).  This page was useful to me:

https://help.oclc.org/Metadata_Services/WorldShare_Collection_Manager/Choose_your_Collection_Manager_workflow/Data_sync_collections/Prepare_your_data/035_field_and_OCLC_control_numbers

The format I have seen from one of our sites is **(OCoLC)198765401**

We should be clear that this field is to be populated only with OCLC numbers to match WorldCat records and not identifiers from other cataloging services.

@leebaylis may have more to add.

**Comment by ds10** [comment]
I'll update examples to match your format and add more details.  Would appricate @leebaylis input too

**Comment by gmoger-jisc** [comment]
I would add all of the example from the link provided.  It could be that we just take the number also but I'm not sure yet how we are going to be using this field to tie in to any other systems.  Presumably it is there as a reference for the sites to use themselves, in which case they will know what it is.

**Comment by ds10** [comment]
Updated the example number but not the text yet, do you want to link to that documention, is worldshare the platform institutions use?

The iri on this seems also seems wrong, I'm not sure where http://oclc.com/number has come from? OCLC don't even seem to own the domain.  Should we be minting a uri for this?

**Comment by leebaylis** [comment]
I threw that IRI in whilst I was waiting for OCLC to come back with an IRI -- they suggested 

https://www.oclc.org/support/services/batchload/controlnumber.en.html

but I see that has already gone stale! I will ask them again.

**Comment by leebaylis** [comment]
worldshare is the platform some institutions use, but not all. OCLC number exists for most borrowable things and is a useful hierarchy -- OCLC's online APIs are useful for cross-referencing materials...

**Comment by ds10** [comment]
Todo:

1. Link to description

2. Lee to return with iri

**Comment by leebaylis** [comment]
Have asked OCLC for comment!

**Comment by ds10** [comment]
From weekly call: @gmoger-jisc and @leebaylis to discuss and report back on valid values.

-  Either it will be OCLC with prefix
- Or add another field to describe which classfiication system

**Comment by leebaylis** [comment]
Response from OCLC regarding what the IRI should be:

I’m very sorry to be so long in responding.  We had a bit of discussion about it right before I was out on holiday and then at a long conference.
At this point the most appropriate link to the description of the OCLC Control number would be from the OCLC glossary:
https://help.oclc.org/Librarian_Toolbox/OCLC_glossaries/OCLC_glossary#O where it states:
 
          OCLC control number
A unique accession number assigned by the OCLC system when a record is added to WorldCat. Used to search for records.

**Comment by gmoger-jisc** [comment]
this is no longer part of the specification
