### ISSUE TITLE
vle-assignmentgraded-template.json: incorrect success item

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#252]
vle-assignmentgraded-template.json has:

```
"result": {
		"score": {
			"scaled": "**SCORE_SCALED**",
			"raw": "**SCORE_RAW**",
			"min": "**SCORE_MIN**",
			"max": "**SCORE_MAX**"
		},
		"success": false,
		"completion": true,
		"response": "**SCORE_RESPONSE**",
		"extensions": {
			"http://xapi.jisc.ac.uk/grade": "**GRADE**"
		}
```

I'm pretty sure that '"success": false' is wrong (if used, it should be a variable, not fixed). In any case:
- it's deprecated in common structures
- it's not in the TSV template.

I suggest just remove this from the JSON template, as it's potentially confusing.
We may have to leave it as deprecated in the common structures, as it may be used elsewhere.

**Comment by arc12** [comment]
+1 for removal
+1 for leaving deprecated

**Comment by ds10** [comment]
From call:

Remove
