### ISSUE TITLE
Moodle and Blackboard examples dont follow spec

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#255]
For discussion at weekly call:

The moodle and blackboard examples don't follow the spec in the master branch. We've spoke about them being behind the spec before, I'd just like to raise this again:

- Should we only have output examples in the master branch if they are upto date
- Should they be sign posted more clearly to explain why they don't follow the spec.

**Comment by ds10** [comment]
From call: Take new outputs and compare, create diff. Gareth to supply outputs.

**Comment by camwestwood** [comment]
Have sent updated Blackboard xAPI examples across to Cetis for update on the documentation page.
