### ISSUE TITLE
TSV descriptions for Setting and Reaching Targets

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#256]
The mobile app statements are going to be 'setting and reaching targets' in 1.0.2, we havne't had  stab at these yet.

Do we have an idea of what these should include?

**Comment by arc12** [comment]
anticipating the future: discriminate between a self-assert claim "I reached target" from an authority "X reached target". I suppose setting could also account for autonomous target-setting being different to agreed (student + tutor) target-setting.

**Comment by ds10** [comment]
From call: This will be co developed with self regulated learning etc in Jisc. Not high prority, but think through flow and have a stab at inputs for the purpose of the discussion.

**Comment by ds10** [comment]
Created, scope to be decided at a later date
