### ISSUE TITLE
Remove additonal items from attendance statement template

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#269]
Feedback from @alleycat58uk: attendance statement is overkill.

It seems the TSV and json template have less in it them than the statement template, the template and tsv came from the original jisc tools repository, why are they different? Was there a decision to cut back data collected to miss some options?

@gmoger-jisc  sugguested we cut back the statement template to match TSV and json template. 

Otherwise we could sign post optional stuff better?

Thoughts?

**Comment by alanepaull** [comment]
In principle, other docs and examples should match the specification; we shouldn't adjust the spec to match examples or other materials.

If we think that the statement template spec is wrong, then we need to discuss and decide on amending the specification.

I think we need to have a proposal!

**Comment by ds10** [comment]
Yes sorry this was written on the call! I think during the call we had thought that when they were in seperate repositories (spec templates and json templates), that development of the spec had happened seperatly and that whoever was doing the json templates might have made a call we werent aware of.

But you are right, the statement templates should be the source of truth.

**Comment by ds10** [comment]
The additional items are still part of the spec, they aren't in the JSON template or TSV because they aren't supplied to jisc yet.

The additional items are all context extensions and no need for institutions to panic about them..
