### ISSUE TITLE
timetabled events that aren't part of a course

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#270]
Feedback from @alleycat58uk,  the attended statement has an (optional) courseArea, but not all timetabled events belong to courseArea. It could be submitted without, but makes it hard to analyse on the way out.

Do we need something optional that can be included instead of courseArea that allows an instition to define its own sort of events? Training ones etc? Paul points out there are some categories that have multiple courses etc.

**Comment by ds10** [comment]
This is good feedback, but we need a requirements gathing phase, @gmoger-jisc is going to engage with sites through project managers for feedback

**Comment by ds10** [comment]
Monthly call update: identifying key partners to work with on this, will mostly follow attendance, but with additional info

**Comment by alleycat58uk** [comment]
One other problem we've noticed with the attendance definitions is a lack of a timetabled event definition which I guess should be part of the UDD maybe?

**Comment by gmoger-jisc** [comment]
This is what we are talking about here but we would see it along the same lines as the attendance recipe but will need to be adapted.

**Comment by gmoger-jisc** [comment]
The attendance recipe we have at the moment is for timetabled events that relate to a course/module.  At least that was the original conception.  This is defined in the purpuse:
https://github.com/jiscdev/xapi/blob/master/recipes/attendance/attendance.md

We also capture the event type to provide groups or categorisation of events, such as lectures, workshop etc.

The question we have now is whether we need 2 recipes (1 or timetables/course related and another for different types of events) or whether we can expand the existing recipe to capture more broad types of events.

Any thoughts on this?

**Comment by alleycat58uk** [comment]
@gmoger-jisc looking at the purpose in attendance.md I see the following:
> to record a learner's attendance of an event such as a lecture or other learning activity

In my mind this is not a course or module but should relate to it.

I think what I'm leaning towards is a definition in the UDD for a timetabled event.  This could be recorded in the context section.  The coursearea (ie module_instance_id from study goal in the Jisc implementation) is optional and, if required/applicable at application level, could be derived from querying UDD.  Equally it could be included (as it currently is) where required/applicable.

This solution would mean additions to the UDD but would result in a single attendance recipe able to cope with course and non-course related learner events whilst staying true to the xapi pattern/principle mentioned by @arc12.

Additionally, if a timetable event table was added to the UDD it would then be possible to add a second table detailing students who should attend.  This would cope with help to cope with non-attendance at split sessions which we have come up against. 

Sorry, gone a little of xapi topic here but this is the context within which we are trying to operate.  I hope it makes sense!

**Comment by alanepaull** [comment]
In addition, I believe that most (all?) of the data in the UDD is from student record systems. These are unlikely to hold the details of timetabled events, so we may have an additional problem of getting this data into the UDD easily.

**Comment by ds10** [comment]
From call:

- One template, have clear sign posting that says object.definition.type is the key way we tell different types of events. Repurpose the purpose.

**Comment by alanepaull** [comment]
I've had a crack at a new Purpose for the attendance statement and amended the object.type.definition. See Pull request: https://github.com/jiscdev/xapi/pull/282.

**Comment by ds10** [comment]
From dec call:

- merge pull request
