### ISSUE TITLE
Attendance recipe - capture time

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#273]
Can we look at an extension for the attendance recipe that will accommodate the time a student attended something, as opposed to the start time of the event which is what we currently capture?

With the Study Goal check-in app we can capture the actual time someone has registered their attendance on an event but do not have somewhere to store it in the recipe.  While we would call this 'check-in time' in study goal I think that anything we implement here should be platform agnostic so perhaps we can call it 'capture time' (any ideas on that welcome).

Incidentally the xapi records do have a stored time which can be used as a de facto check-in time and should match what Study Goal produces.  But that would not be the case if we manually loaded data from other systems.

Is this best placed as a result extension or an object extension?  My thinking is with result.

**Comment by gmoger-jisc** [comment]
I agree on scope and is in line with what we have discussed here.  Not all systems will be able to provide this but for those that can it is a worthwhile extension.

I think 'capture time' is broad enough to apply to swipe card, phone based or other attendance systems.  'time attended' is another option but I don't think this would be accurate in the sense of phone based check ins (a student might have arrived on time but not check-in until the end of the event).

**Comment by ds10** [comment]
I think I put this in an early draft but can't remember the discussion around it. I'll have a look at previous drafts and put something in 1.0.2 by the end of the week for discussion at our next monthly call.

**Comment by ds10** [comment]
I'm comitting this to the dev 1.0.2 branch. I couldn't actually find this exisiting before, so if it existed as a draft it may have been before we started version control.

I think scope and semantics are important too, so I'll have a shot at an iri and a description but I think we need to talk them over at our next call. 

I'll go with something around capture time, I had these thoughts on the other
- Time attended may be different than the time somebody actually registered their attendance
- We may have different understanding of what a checking in time is. I think of it as a time registration is avalible from (a check in time at an airport or hotel)

**Comment by gmoger-jisc** [comment]
Yes we need to be clear on the distinction between all of the time elements.  Let's review on the next call.

**Comment by gmoger-jisc** [comment]
As an example, with our Check-In app, the timestamp refers to the time the event is scheduled and will be the same for all student records on that event.  The 'time captured' would specifically be the point at which the student registered their attendance.

**Comment by ds10** [comment]
From call:
- start time and timestamp are the same, they stay the same
- student registration/capture time/attendance logged by student is the time in which the attendance information was captured by the student

**Comment by ds10** [comment]
I've added capture time to 1.0.2 as a result extension that records the time the result was captured. I remember everyone agreeing capture time is fine, but I also remember that capture_time will only ever be captured by the actor and not a third party. Example the student will set the capture time and it will never be inputted by register etc. This was important to Jisc because you wanted to capture the time that pupils recorded attentance, so we can't allow capture time to be a time registration was recorded by anybody: so I propose changing it to something else, submited time/actor submitted time?

- how about submissionTime: the time the result was submited by the actor

**Comment by gmoger-jisc** [comment]
Yes that sounds fine.
