### ISSUE TITLE
Borrowed items - additional items

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#275]
I received data form 1 site which detailed the library the item was borrowed from (as there are many sites at the institution).  They also provided the subject area of the item.

It seems as though this is quite standard information in Library Management Systems but we will need to get consensus on that.

I think both of these would be useful in our analytics so it may be worth revisiting this recipe to see what we can accommodate.

**Comment by ds10** [comment]
I'll update 1.0.2 for us to have something to talk about while you get consesus. Double checking

- Is 'borrowed from' a string to identify?

**Comment by ds10** [comment]
ok, I've just checked in the template for 1.0.2 library borrowed, but need to think about uri'sand the such. plus and what we are collecting, so I have not updated the input files or descriptive mark down. I'd like input from everyone, perhaps at the next call. I've mostly looked back at previous drafts. 

- It feels like there should be something to reuse for library subject areas/categories, I was sniffing around: http://id.tincanapi.com/activitytype/category but I think that approach uses contextActivites to describe the subject area and is overkill, I don't think that we are there. So, I've gone with context.extensions.http://xapi.jisc.ac.uk/library_borrower_category that was thrown out of the inital library borrowing draft.

- Gone with context.extensions.http://xapi.jisc.ac.uk/library_branch that was thrown out of the inital library borrowing draft

I think the 'feature branches' are stale as we have reverted back to having a master branch and dev branches, so we might want to revist what we are doing with them. Having said that the library feature branch shows a stab by myself and lee at some of these things after Lee had a chat with vendors: https://github.com/jiscdev/xapi/blob/feature-library/recipes/library/library-item-borrowing.md

**Comment by gmoger-jisc** [comment]
'borrowed from' should be the specific library where each institution will have their own reference this (it could be codified if they wanted to return it that way).

I don't have more knowledge on reading lists yet so I am not sure what the data would look like.  I am assuming that each list would have a unique id and linked to a module instance but we need to review the data before we can confirm that.  I will follow up on that later in the week.

**Comment by ds10** [comment]
For November 5th Call:

The JSON template in the 1.0.2 branch brought in the following from the library feature branch:

- object.definition.extension.http://xapi.jisc.ac.uk/dewey_code
- context.extensions.http://xapi.jisc.ac.uk/library_branch

Are these what we needed, seems odd to be minting a uri for dewey? 
Ok to put these in markdown and TSV definition?

**Comment by gmoger-jisc** [comment]
What is the dewey code?

**Comment by ds10** [comment]
From call: 

- Switch from dewey to a freetext category (investigate categories with Lee )
- Switch from library site to 'borrowing site'
- update md, tsv definitions and vocab

**Comment by ds10** [comment]
I've followed the term call discussion by addeding subjectArea and borrowingSite as we discussed on the call. But some thoughts:

- subjectArea is an object extension the subject area of the object, is category better?
- borrowingSite is a context extension, "site object was borrowed from", is 'checking out' better than borrowed?

**Comment by alanepaull** [comment]
We already use subjectArea with a different context, so I think "category" would be better.

**Comment by ds10** [comment]
I thought we had minted a subjectArea, but I can't find mention of it in the spec, where do we use it?

**Comment by alanepaull** [comment]
Ah, maybe I'm thinking of courseArea? Just searched the xAPI files for subjectArea, and no occurrence in v1.0.1. So, perhaps subjectArea is OK? Unless others might get confused like I did. In which case, category would get my vote.

**Comment by gmoger-jisc** [comment]
I don't have a problem with subjectArea and think category would lead to more confusion (e.g. mixing up with type)

Given this is a borrowed items recipe I think borrowingSite is appropriate.  Not sure why 'checking out' would be better.

**Comment by gmoger-jisc** [comment]
No, you don't checkout e-content; you would view it or access it.  I understand your thinking on cross statement usage but not sure we will find something that fits across everything.

**Comment by ds10** [comment]
For Dec 3rd call:

two new values:
object.definition.extensions.http://xapi.jisc.ac.uk/subject_area [0..1]
context.extensions.http://xapi.jisc.ac.uk/borrowing_site [0..1]

Are these ok? are they the right place for them?

**Comment by gmoger-jisc** [comment]
yes that's look good.
