### ISSUE TITLE
Study apps has no statement category

### ISSUE THREAD

**Issue by alleycat58uk** [jiscdev/xapi#278]
There is no statement category defined for the [mobile_app_content_viewed](https://github.com/jiscdev/xapi/blob/master/recipes/studyapps/mobile-app.md) recipe.

In all other recipes this is defined as: `statement.context.extensions.http://xapi.jisc.ac.uk/statementCat` for example the [VLE login recipe](https://github.com/jiscdev/xapi/blob/master/recipes/vle/login.md#context)

**Comment by ds10** [comment]
Good catch, the statementCat should be optional in the spec but not required in the TSV. It should be set to app in the jisc template. Will update this

**Comment by ds10** [comment]
For Dec 3rd call:

This is a small documentation error:

statementCat is used by Jisc to categorise statements, but is not provided by institutions in TSV as jisc set it in the json template. The description is missing from the study apps markdown but in other recipes it is currently:

_Recommended For querying lookup. Set to category of statement_

Description should be added to study app md

**Comment by ds10** [comment]
From call:

yes, put this in to the markdown file
