### ISSUE TITLE
Attendance Recipe - field to capture device

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#281]
With other amendments going on to the recipe (capture time and platform) can we also look at add an extension to record the device e.g. Web/Android/IOS.  Right now this is more important from a validation perspective (investigating issues etc) but other use cases for analytics might be developed later.

**Comment by ds10** [comment]
Is this optional and a from a controled list of: web/android/ios?

**Comment by gmoger-jisc** [comment]
Yes this would be optional and I do not believe there would be a controlled list

**Comment by ds10** [comment]
from call:

optional, no controlled list

**Comment by alanepaull** [comment]
I think that captured_from is the platform that was used for the capture. So, it would be populated from the system, in some way. It's in the TSV spec, which I presume is correct, though it's not a traditional variable (in other words, it wouldn't vary on a student by student basis, but on a system or log basis).

Can Gareth confirm that it should be in the TSV spec, and not picked up (like perhaps context.platform) via another method on import of a particular file type or log type?

**Comment by gmoger-jisc** [comment]
No this would not be in the TSV for import.  It it only where we want to capture additional information of a users device when they are interacting our 'check-in' app.

**Comment by ds10** [comment]
context.extensions."http://xapi.jisc.ac.uk/captured_from" added to vocab, in md and JSON, but not TSV definition
