### ISSUE TITLE
release v1.0.2

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#284]
With the exception of ticket #277 , which is moving statements to 1.0.3, 1.0.2 tickets have been closed off. 

There is quite a few small changes and a new statement template in 1.0.2, the changes are all tracked in the 1.0.2 version_changes document, which I will pull out for release notes.

I am happy to do the required merges and push 1.0.2 to master next week as discussed (minus the target setting statements).

The caveat from my end is work in 1.0.2 (as far as I know) hasnot been through any testing process on the Jisc side, thrown at a LDH etc. I think statements such as the mobile app content viewed still haven't been tested since they were added in 1.0.1. 

For the 1.0.1 release Jisc asked us to release and hotfix based on Jisc feedback, Gareth gave the impression that the approach was to be the same.

If there is a nod to this approach, a release of 1.0.2 will take place on 11th of Dec

**Comment by gmoger-jisc** [comment]
Yes this all sounds fine.

I have already tested load to the LDH of the e-content recipe without issue.

**Comment by ds10** [comment]
released here: https://github.com/jiscdev/xapi/releases/tag/1.0.2

This has been merged in master and the 1.0.2 dev branch will be deleted
