### ISSUE TITLE
Activity type for groups in VLE

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#286]
In some VLE systems you have the concept of groups, such as this from Canvas:
https://community.canvaslms.com/docs/DOC-10717

> Groups are a small version of a course and used as a collaborative tool where students can work together on group projects and assignments.

I cannot find a sensible activity type to use for these events.  Can you reccommend something or do we need something new?  I could just log it as 'other' but I think we would lose useful information.

https://github.com/jiscdev/xapi/blob/master/vocabulary.md#activity-types

**Comment by arc12** [comment]
this is calling to as: requirement = recipe for collaboration spaces
I agree: just bucketing as a non-specific resource view is not really a good fit

However: semantic models for collaboration get messy very fast, so I;d be inclined to model this fairly non-specifically in terms of what was done to what... e.g. keep it as simple as "did something [active] in a collaboration space"

**Comment by gmoger-jisc** [comment]
Agreed to keep it simple which to me means adding an activity type of 'collaboration_space'.  We can capture more detail in the subtypes if necessary.

**Comment by ds10** [comment]
I don't know the use cases here, so just checking I understand this:

What **we are** talking about is a new statement template for: 

`Agent (Actor) did whatever (verb) in collaboration_space (object)`

What **we are not talking** about is the xAPI actor objectType 'group', which can be anonymous or identified which let us say:

`Group (Actor) did whatever (Verb) in whatever activity (object)`

Or

`whoever (Actor)  did whatever(Verb) to Group (Object)`

**Comment by gmoger-jisc** [comment]
The first one:
Agent (Actor) did whatever (verb) in collaboration_space (object)

That collaboration space should be attached to a course/module however so I'm not sure if the object needs to be the space or the course/module.  There would also be subtypes to define what the have done in the space e.g. group files, group discussions etc.

**Comment by alanepaull** [comment]
I think we can cover the course/module with the courseArea extension.
If it's "Agent (Actor) did whatever (verb) in collaboration_space (object)", then the courseArea fits in context. And a subType for the collaboration_space object makes sense.

**Comment by ds10** [comment]
I was just mocking up something in 1.0.3 for us to talk about, but I'm not sure I fully get it yet.

I started by creating a new statement template under the VLE recipe for collaboration_space. But that statement doesn't really fit the flow of the repository. The statements under VLE really revolve around different verbs, the verb in each statement is consistant, but there can be different activities. For example, I think in graded statement it is the scored verb that is important, and the type of thing that is being graded could change?

The statement:

`Agent (Actor) did whatever (verb) in collaboration_space`

switches this around and makes the object the constant.

Should collaboration space be a new activity type in the dictionary rather than a new statement. For example could it be an activity type for the graded statement?

**Comment by gmoger-jisc** [comment]
Yes, I never imagined this as a new statement (as per discussion above); it just needs a new activity type from my understanding.

**Comment by ds10** [comment]
Got you. This is tagged as discussion for next call, but I will mint a jisc iri for collaboration_space in 1.0.3 for us to discuss then

**Comment by ds10** [comment]
For Feb 5th call:

The following was added to the vocab

<table>
<tr><th align="left">Label</th><td>Collaboration Space</td></tr>
<tr><th align="left">Description</th><td> A collaborative space where students can work together on group projects and assignments. For example <a href="https://community.canvaslms.com/docs/DOC-10717">Cavas Groups</a></td></tr>
<tr><th align="left">IRI</th><td> <a href="http://xapi.jisc.ac.uk/collaboration_space">http://xapi.jisc.ac.uk/collaboration_space</a> </td></tr>
</table>

* Double check requirements, is this just a different object that fits in to exisiting VLE statements? This is not a new statement
* are examples required anywhere (I'm not sure of use)
* Check this is not about the xapi concept of groups in the agent
