### ISSUE TITLE
Value of statementcat in Econtent statements

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#294]
Currently in the econtent recipe statements (accessed service and viewed econtent)  the spec and JSON templates has the value of optional property context.extensions.statementCat set to the string "Library". This may be because I had always seen the econtent statements as part of the jisc library recipe. However, in the documentation it looks like the econtent statements are part of a seperate recipe.

The context.extensions.statementcat was put in by Jisc as an option context extension for all statements for querying purposes. So the question is:

**What should the value of statementcat in Econtent statements be?**

Are they part of the library category, or should there be a seperate elearning category?

But I think it raises a wider question I was trying to get at on tuesdays call, I had tried to raise at the meeting a conversation around 'whats included in a recipe'. The general feeling was that reading list was different from library. Is this because they come from a seperate datastream? Is that what defines a recipe?

Another question: is a category different to a recipe?

**Comment by arc12** [comment]
sitting on the sofa of pontification....

I think "library" is not a helpful category, and that we should consider recipes to be aligned to online services; "library" feels like a term for an organisational unit which may operate several services, including (historically, but not necessarily) reading lists. I feel a recipe should be a good match to "whats in the database for {system X}".

So: "library loans" might be a service, so might "econtent", and "reading list", and all have their own recipes, but re-using several statement templates.

**Comment by ds10** [comment]
While on the softa:
* In terms of the layout of the repository:

I think thats where we are heading currently, we are getting to a point where the statements in each seem like they are repeats of the same statement templates (viewed econtent, viewed vle, viewed video). Perhaps at this stage the repetition doesn't matter because we do have a link on each to the  'generic template' and the examples in the recipes are relevent to that recipe. 

* In terms of what is a helpful category:

Jisc requested the statementcat element, is that the same as the recipe? Or do the analysts have a different purpose for it?

Off the softa on to the treadmill of procedure:

* Are the current statementcats/recipe headings ok
Adam has raised that library as a statementcat is actually not very useful, I don't really know what they are used for and what the implications of changing them now are, but expect we need to change econtent statements from library.

**Comment by gmoger-jisc** [comment]
I don't believe this is being used by us anywhere but will need to investigate further before I can confirm.  I think it could be a helpful way of categorising groups of recipes from a documentation perspective but also for us to more easily group activities when looking at the data (without having to map all the elements to determine a grouping).

Somewhat related, I'm not sure why the e-content stuff was separated from library borrowed as these exist in the same category in my mind (most digital resources that we would want to track activity from will be maintained by library systems teams).

**Comment by ds10** [comment]
> so for us to more easily group activities when looking at the data (without having to map all the elements to determine a grouping).

I think this was why michael added it.

> Somewhat related, I'm not sure why the e-content stuff was separated from library borrowed as these exist in the same category in my mind (most digital resources that we would want to track activity from will be maintained by library systems teams).

They are only seperated by different headings in the readme, sugguesting they are different recipes. They currently have the same statementcat, and are in the library subdirectory

**Comment by alanepaull** [comment]
I think this is the important question (just for clarity): "Jisc requested the statementcat element, is that the same as the recipe? Or do the analysts have a different purpose for it?"

I suggest that we should all be clear that a recipe is a bunch of statement templates within some form of cognate group; for example, the "VLE" recipe has a bunch of statement templates that are pertinent to VLE activity data; "video" refers to statement templates for video activity data. **If needed**, we could arrange a constant within each statement that states the recipe that the statement template is in.

On the other hand, if statementCat is an attempt to cut the statements along a different axis, then the different name ("statementCat" rather than "recipe") makes sense. Again, **if needed**, we could implement that in a similar way to the previous paragraph.

**Comment by gmoger-jisc** [comment]
statementCat is not being used in any way currently but the intention was/is for it to be used to group the statements in line with how they are presented in the documentation e.g. VLE, Library etc..

Does it really matter that we call this statementCat as opposed to recipe?

The original question was:
_What should the value of statementcat in Econtent statements be?_

As most digital resources such as e-journal access, ebooks and other content are maintained by library system teams it makes sense in my mind to keep them here, either as 'Library' or better as 'Library Services' perhaps, as per Adam's comment.

**Comment by ds10** [comment]
For call:

statementcat was added by Michael in issue #225 to "to make querying easier." Originally it fell into one of three valid values:  Attendance, VLE, Library 

Econtent statements are the only one with a different value in there other than then the recipe name.  I think my thinking was that library systems house the content:

- VLE Recipes have cat: "VLE"
- Econtent have cat "Library"
- Library has cat "Library"
- Readinglist is "Readinglist"
- Intervention is "Note" (We did decide that we wanted the first stab of intervention statements to have a more 'generic' name, but keep intervention as the heading in the documentation)
- Attendance is "Attendance"
- Video is "Video"
- Setting amd reaching targets don't have JSON templates

So:

- should econtent stay as library,
- Are the other others ok, if so Readinglist, Note and Video need adding to the vocab

**Comment by ds10** [comment]
From call:

- depricate this and replace with something along the lines of recipeCat: 
- Add what we mean by 'a recipe' to documentation

**Comment by ds10** [comment]
For call April 1st:

- statementCat has been deprecated in 1.0.3
- recipeCat has been minted, updated documentation, templates & examples in 1.0.3
