### ISSUE TITLE
Rename tracking app

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#299]
https://github.com/jiscdev/xapi#tracking-app

Can we please look to rename this recipe to something more appropriate, such as "Mobile Applications"?  There is no tracking app.  We are simply looking at activity from within mobile apps.

**Comment by arc12** [comment]
TBH I'm rather unconvinced by the concept, period!

This is just an "actor viewed a resource on a platform" statement.
Arguably "mobile" is just an aspect of context of access. IF I were to have a Moodle app then the statement would follow the VLE recipe, would it not, with platform=Moodle, and the "mobile app" distinction drawn elsewhere.

**Comment by gmoger-jisc** [comment]
Agreed.  Maybe we need to reconsider the VLE resource viewed also to make this more generic as simply 'resource viewed' where platform/device can be recorded as part of that.

**Comment by ds10** [comment]
For April 1st call (perhaps earlier if this is straight forward
- I was under the impression there was some kind off app in development and these were to support that.

Questions:
- What is the purpose of this recipe?
- We have 'generic statements' folder, which has statements for things like viewing, that doesn't have recipe information in them. I think this is currently used more as reference when writing a new statement. Should these be more integrated into the documentation?
- Should it be renamed, removed? Is viewed in generic statements more like what we in the docs?

**Comment by gmoger-jisc** [comment]
Yes the app is 'Study Goal' and this recipe is used to capture activity around screen views however it is not actively being used at the moment.

Happy for things to be more integrated.

What do you recommend in how to mange this?  My issue is only really in the name so let's sort that first of all and then look at structural changes.

**Comment by ds10** [comment]
renamed in 1.0.3, 

- In 1.0.3, the statements share the same folder ('studyapps') as the target setting statements. I think the history of this is that the target setting staments and viewed content were developed to support studygoal, but neither have been active. For some reason, the viewed statement made it in to 1.0 as a tracking app statement,  while the others have stayed in the dev branch as target setting statements.
