### ISSUE TITLE
URL should be HOSTNAME on accessed service

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#309]
https://github.com/jiscdev/xapi/blob/master/recipes/library/uxapi/library-accessed-econtent-input.md

I think we agreed not to capture the full URL and instead just the hostname as the object ID?  As such can you please update the spec.

**Comment by ds10** [comment]
Yes I think that is what was agreed,

Wondering If the reason behind this is that I'd thought you were asking institutions for the full url and then doing a bit of regex for the hostname

**Comment by gmoger-jisc** [comment]
That's what I do with some log files but thought the input should reflect the end result?  If not then better to include HOSTNAME and URL and I can parse those that cannot capture the host themselves (host is returned with exproxy logs and shibboleth already).

**Comment by ds10** [comment]
_thought the input should reflect the end result_

Yes, I think this is right? It also reflects what you expect from the institution? I'll make the change

**Comment by ds10** [comment]
Made change - closing ticket
