### ISSUE TITLE
Discussion: Econtent services recipe

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#310]
The econtent services recipe is based around institutional systems that essentially just log in -eproxy etc. I am unsure if I understand the functionality of eproxy and similar systems and would like to  I bring up the purpose of this recipe.

We have discussed:

* Recipes are statements grouped around types of institutional systems (VLE systems/video systems/attendance systems)
* It’s acceptable to have the same statements for different recipes, which are the same statement - but perhaps with different examples. For example, you could have a login statement in both the VLE and attendance systems.
* The econtent services is based around systems like eproxy which, as far as I understand is just for logging in, so it is more just a statement than recipe?

I have some questions/comments:

* If econtent is just ‘logging in’ should it be a statement that part of other recipes as a logged in statement?
* If so, what happens to the recipe based around proxy statements. Originally, I put econtent under ‘library services’, but it was moved out because the group decided that it isn’t a library system statement, it belonged to proxy systems.
* But.. proxy systems seem like a very wide category of systems. People coming to the spec with logs from a proxy system might completely different types of data?
* Have I completely misunderstood ‘econtent services/proxy systems’

**Comment by gmoger-jisc** [comment]
I think e-Content Services makes sense (but not tie in the proxy systems - see below).  Then the statements would include 'logged in' which we would obtain from the authentication logs and 'resource viewed' which we would potentially obtain from other systems (such as reading lists).

Authentication might form it's own recipe then, with a generic logged-in statement which could be used.  This data would come from shibboleth, ezproxy logs etc where there may be an overlap between the e-content access above.  We will have to manage that in our integrations.
