### ISSUE TITLE
Logged In statement for mobile app recipe

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#311]
Can we look to add a 'logged in' statement for the mobile app recipe.  This will need to include device information for use in debugging issues.  That will come in the form of the User Agent string:

https://en.wikipedia.org/wiki/User_agent
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent

For example:
Mozilla/5.0 (iPad; U; CPU OS 3_2_1 like Mac OS X; en-us) AppleWebKit/531.21.10 (KHTML, like Gecko) Mobile/7B405

**Comment by matt-cownie** [comment]
hi, we would also like to add an optional field to the statement record if the device is jail broken

**Comment by gmoger-jisc** [comment]
Where does that information come from and what does it look like?

**Comment by matt-cownie** [comment]
the mobile client will work it out and use True/False ?

**Comment by matt-cownie** [comment]
thinking on it a probability score i.e. 0-100 is more flexible

**Comment by gmoger-jisc** [comment]
So you will be testing for jailbreak within the app and then posting the result?  I guess the result will depend on how good the tests are and whether that will lead to a probably score or just "likely to be jail broken - true/false".

**Comment by arc12** [comment]
Matt -
I'd seek advice on this from someone with a view of privacy protection.
My own view is that the "jailbreak" status of a phone is NOT a matter of legitimate interest for a provider of education. As such it is likely to open up new perspectives on GDPR which might muddy the waters...

**Comment by gmoger-jisc** [comment]
Raised with our Andrew Cormack our chief regulatory adviser to see what his view was and got a speedy response:

> Depends why you need the information, and what the process leading up to that is. Two contrasting (real!) examples:
> 
> a) we need to know (among other things) if a phone is jailbroken to assess the security risk of letting it connect to the internal network (this is currently being looked at in Jisc). In that case it is a legitimate interest of the network provider and the check needs to be done each time the phone connects. But information doesn't need to be stored beyond the current session; indeed relying on the fact that it wasn't jail broken *last* time it connected is actively misleading;
> 
> b) we need to know (among other things) if a phone is jailbroken to assess whether the phone's config is causing problems that the user has asked us to debug. Here the best route is to ask the user, when they report the problem, "may we check your phone's configuration, to see if that's the problem?". 
> 
> c) may be others...
> 
> I'm struggling to think of a reason that would justify keeping the jailbreak status of all phones, just in case one of them reported a problem.
> 
> Note, by the way, that a new law on accessing data from end-user devices, including phones is currently being debated. They do, at last, seem to have got the message that security patches and checks need to be permitted, also logs, but it's taken three years of nagging to get those into the drafts! But details are still subject to change. Very likely that whatever comes out, we'll need to document what settings, etc. are accessed in either of the above scenarios
>

**Comment by matt-cownie** [comment]
ok, we where thinking b) 

so the steer is not appropriate, which is fair, its not really any of our of our business until the system doesnt work for them and even then that might not be the root cause

**Comment by ds10** [comment]
So we want:

* Logged in statement geared towards mobile app recipe with appropriate example
* To add optional browser information to the log in statements

Are we looking at an [object in the context which has browser information in key pairs](http://id.tincanapi.com/extension/browser-info), or just a string like in your Mozilla link?

Can we talk about jail broken requirement? If you are only sending the data on request when there is a problem, is this outside of scope to be captured by the LA statements?

**Comment by ds10** [comment]
Just to clarify the approach:

- Add logged in statement to mobile app recipe
- add optional browser info to common structures

**Comment by matt-cownie** [comment]
Thought about that, string is more future proof
I think the jailbroken requirement will be dropped and/ot is outside the scope of LA Statements

matt

**Comment by ds10** [comment]
- logged in statement for mobile app
- add browser information to context  to common statements
