### ISSUE TITLE
Sentiment statement

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#312]
From our mobile application we would like to capture how a student is feeling at different points in time.  The statement would simple show the following categories:

- Very happy
- Happy
- Sad
- Very Sad

We would want need to capture the platform and device information also in line with this call:
https://github.com/jiscdev/xapi/issues/311

David - can you advise on what the verb/object might look like for this?

**Comment by ds10** [comment]
This sounds like it is a submission of a question?

We have two statements in the VLE recipe, one for is for [answered question](https://github.com/jiscdev/xapi/blob/master/recipes/vle/answered_questions.md)

so the  sentement would be the answer found in the result entity, is that right? **Something like** this?

```
{
"actor": {
	"objectType": "Agent",
	"account": {
		"name": "jsmith12",
		"homePage": "https://app.jisc.ac.uk/"
	}
},
"verb": {
	"id": "http://adlnet.gov/expapi/verbs/answered",
	"display": {
		"en" : "answered"
	}
},
"object": {
	"id": "http://app/sentiment/quiz1/question1",
	"objectType": "Activity",
	"definition": {
		"interactionType": "choice",
		"type": "http://activitystrea.ms/schema/1.0/question"
                 "choices": [
		         {
			"id": "Very Happy",
			}
		},
		{
			"id": "Happy"
			}
		},
		{
			"id": "Sad"
			}
		},
		{
			"id": "Very Sad" 
			}
		}

	}
},

 "result": {
	"response": "Sad",
},

"context": {
       "platform": "Studygoal",
	    
	"extensions": {
	    	"http://xapi.jisc.ac.uk/statementCat": "App",
	},
				
	"contextActivities": {
	        "parent": [
	        {
		"id": "http://app/sentiment/quiz1/"
		}
		]
	}
}
}
```

The other is for a[ submission of a quiz](https://github.com/jiscdev/xapi/blob/master/recipes/vle/quiz_completed.md), so if there were multiple questions, you could submit the answer to each as above, and then once the full quiz is completed submit a quiz completed statement.

Would like the groups thoughts later today.

**Comment by gmoger-jisc** [comment]
The question will be 'How are you feeling today?'.  This may change to 'How are you feeling about your course today?'.

**Comment by ds10** [comment]
Should this just be an interaction activity: [https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#interaction-activities](https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#interaction-activities

Question name and description can go in the object:

)

```
{
"actor": {
	"objectType": "Agent",
	"account": {
		"name": "jsmith12",
		"homePage": "https://app.jisc.ac.uk/"
	}
},
"verb": {
	"id": "http://adlnet.gov/expapi/verbs/answered",
	"display": {
		"en" : "answered"
	}
},
"object": {
	"id": "http://app/sentiment/quiz1/question1",
	"objectType": "Activity",
	"definition": {
                 "name": {
                             "en": "sentiment"
                           },
                  "description": {
                             "en": "How are you feeling today?"
                             },
		"interactionType": "choice",
		"type": "http://adlnet.gov/expapi/activities/cmi.interaction"
                 "choices": [
		         {
			"id": "Very Happy",
			"description": "Very Happy",
			}
		},
		{
			"id": "Happy"
			"description": "Happy",
			}
		},
		{
			"id": "Sad"
			"description": "Sad",
			}
		},
		{
			"id": "Very Sad" 
			"description": "Very Sad",
			}
		}

	}
},

 "result": {
	"response": "Sad",
},

"context": {
       "platform": "Studygoal",
	    
	"extensions": {
	    	"http://xapi.jisc.ac.uk/statementCat": "App",
	},
				
	"contextActivities": {
	        "parent": [
	        {
		"id": "http://app/sentiment/quiz1/"
		}
		]
	}
}
}
```

**Comment by gmoger-jisc** [comment]
Seems reasonable.

**Comment by alanepaull** [comment]
Though of course http://xapi.jisc.ac.uk/statementCat should be http://xapi.jisc.ac.uk/recipeCat

**Comment by ds10** [comment]
This one has raised some questions about the way we do quizes and questions in vle. This is how I understand thing..

In the example above I use some an interactipn type, with xapi properties (interactionType, choice) that have been included to be comptable with scorm. The spec says of these properties

"These interaction definitions are simple to use, and consequently limited. It is expected that Communities of Practice requiring richer interactions definitions will do so through the use of Activity types and Activity Definition Extensions." it **recommends** http://adlnet.gov/expapi/activities/cmi.interaction as the activity type, when using these properties.

So, the above interaction activity is fine, but it also kind of expects we will probably want to use a different activity type for the interactions, with activity.definition.extensions to capture interaction information.

This also makes me wonder about the VLE quiz ones, where we are using the quiz activity type with these properties.. which is not really what it is expecting, although the way I read the spec, this seems to be allowed.

**Comment by ds10** [comment]
* from call:

- Go with bottom example,
- use quetion type
- remove the quiz parent
-double check spec

**Comment by ds10** [comment]
I've added a mobile answered question statement to the mobile apps recipe. I'd still like to talk about the same issues that we had on the last call, maybe Adam or Ryan have an opinion:

* The statement makes use of interaction activity properties in the object https://github.com/adlnet/xAPI-Spec/blob/master/xAPI-Data.md#interaction-activities
* But it doesn't use the cmi.interaction type that the spec said SHOULD be used when using the interactiontype property
* This is in line with how we've done the VLE questions statement, I think we have spoke about this before but I can't find the conversation on github. 
* I think the spec assumes you'll use object.definition.extensions if your not using http://adlnet.gov/expapi/activities/cmi.interaction as the type

One for the call I think.
