### ISSUE TITLE
Attendance template missing elements

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#315]
Attendance JSON template is missing device location and does not match example in the md page.

**Comment by ds10** [comment]
I think this is a spec vs jisc process problem:

I remember that this wasn't requested originally from jisc originally (but was optional in the spec), so it is in the example because you weren't collecting it. As such it is also not in the TSV definition. 

But, when I raised the issue of spec vs process being different, at our face to face you said going forward all properties, including ones you may not be collecting are to go in the uxapi,because it doesn't matter if they are just blank. If so it is no problem to put this in the json, but may take a little bit of time to check that we are consistent in all the other statements.

For it not matching, The only differences I can see are that devicelocation is missing, and the documentation has vle_course_instance, which is a doc error,  it should be uddcourseinstanceid like the template and vocab says.

**Comment by gmoger-jisc** [comment]
This is what I am looking at (you might need to run it through a formatter as I cannot find a way to pretty print it):

`{
    "actor": {
        "objectType": "Agent",
        "account": {
            "name": "**STUDENT_ID**",
            "homePage": "**HOMEPAGE**"
        }
    },
    "verb": {
        "id": "http://adlnet.gov/expapi/verbs/attended",
        "display": {
            "en": "attended"
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "**HOMEPAGE**/event/**EVENT_ID**",
        "definition": {
            "type": "http://xapi.jisc.ac.uk/event_timetabled/",
            "name": {
                "en": "**EVENT_NAME**"
            },
            "description": {
                "en": "**EVENT_DESCRIPTION**"
            },
            "extensions": {
                "http://xapi.jisc.ac.uk/subType": "**HOMEPAGE**/event_type/**EVENT_TYPE**",
                "http://xapi.jisc.ac.uk/event_type_description": "**EVENT_TYPE_DESCRIPTION**",
                "http://xapi.jisc.ac.uk/event_max_count": **EVENT_MAX_COUNT**,
                "http://xapi.jisc.ac.uk/event_mandatory": **EVENT_MANDATORY**,
                "http://xapi.jisc.ac.uk/starttime": "**START_TIME**",
                "http://xapi.jisc.ac.uk/endtime": "**END_TIME**"
            }
        }
    },
    "result": {
        "completion": **CALCULATED_COMPLETE**,
        "extensions": {
            "http://xapi.jisc.ac.uk/attendance_late": **ATTENDANCE_LATE**,
            "http://xapi.jisc.ac.uk/attendance_category": "**ATTENDANCE_CATEGORY**",
            "http://xapi.jisc.ac.uk/submission_time": "**SUBMISSION_TIME**"
        }
    },
    "context": {
        "platform": "**PLATFORM**",
        "instructor": {
            "objectType": "Agent",
            "name": "instructor",
            "account": {
                "name": "**STAFF_ID**",
                "homePage": "**HOMEPAGE**"
            }
        },
        "extensions": {
            "http://xapi.jisc.ac.uk/version": "1.0.2",
            "http://xapi.jisc.ac.uk/courseArea": {
                "http://xapi.jisc.ac.uk/udddCourseInstanceId": "**COURSE_INSTANCE_ID**",
                "http://xapi.jisc.ac.uk/uddModInstanceID": "**MOD_INSTANCE_ID**"
            },
            "http://xapi.jisc.ac.uk/recipeCat": "Attendance",
            "http://xapi.jisc.ac.uk/captured_from": "**CAPTURED_FROM**",
            "http://xapi.jisc.ac.uk/deviceLocation": {
                "type": "feature",
                "geometry": {
                    "type": "point",
                    "coordinates": ["**LAT**", "-**LONG**"]
                }
            }
        }
    },
    "timestamp": "**START_TIME**"
}`

**Comment by ds10** [comment]
Not sure what you mean this is what you are looking at, is this your correct version? this does have the deviceLocation.

I think:
* DeviceLocation needs adding to files
* Long and lat need adding to TSV binding
* MD files need changing to remove vle_mod_id

does that sound right?

**Comment by gmoger-jisc** [comment]
Yes, this is the version we are using to load data from TSV's but we do not capture geolocation here so the elements are removed during processing.  It's debateable then whether we should include them in the TSV spec.

vle_mod_id should not be anywhere.  Only MOD_INSTANCE_ID and COURSE_INSTANCE_ID.

**Comment by ds10** [comment]
Yes that is correct, but it is in the MD, it should be http://xapi.jisc.ac.uk/uddModInstanceID instead. Needs changing.
