### ISSUE TITLE
enrolment

### ISSUE THREAD

**Issue by alanepaull** [jiscdev/xapi#321]
Currently we have a vocab object: http://xapi.jisc.ac.uk/activities/enrollement

Unfortunately, this is incorrectly spelt. I propose changing the entry to the following, using British English spelling throughout:

### Enrolment

<table>
<tr><th align="left">Label</th><td>Enrolment</td></tr>
<tr><th align="left">Description</th><td>The action of enrolling or being enrolled.</td></tr>
<tr><th align="left">IRI</th><td> <a href="http://xapi.jisc.ac.uk/activities/enrolment">http://xapi.jisc.ac.uk/activities/enrolment</a> </td></tr>
</table>

If this isn't currently being used, then there may be no problem with this change. Is there any current usage of this object?

**Comment by ds10** [comment]
this was minted yesterday and is only in dev branch, no current usage

**Comment by alanepaull** [comment]
I've updated it now.
