### ISSUE TITLE
Accessed building or facility

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#329]
We are looking to capture activities where a student has accessed a building or facility such as a library.  This would most likely come from swipe/rfid card data which we are looking to explore with one of our institutions.  As a starting point I believe these are the minimum fields to capture:

- Student ID
- Timestamp
- Site (location or identifier)
- Type (library or service grouping)

I have not been able to explore any data to see if there is anything more worth capturing but I want to start the conversation here.

This seems most appropriate with an 'accessed' verb:
https://registry.tincanapi.com/#uri/verb/81

However we are also using this for 'accessed service' with authentication requests so I want to make sure that with anything we implement here we can correctly distinguish between the activities.

**Comment by ds10** [comment]
I'd like to hear other peoples views too,

I'll have a think and a poke around, then report back, but inital thought is that it makes sense to me if they are accessing the object.

**Comment by arc12** [comment]
The general idea gets my thumbs-up.

Some quick reactions on detail:
- is this limited to gaining access = "entering", or do we expect there is also the potential to swipe-out?
- is there a conceptual similarity to presence determined from WiFi access point connection? i.e. a case for similar pattern?
- for the location type vocab, I think it would be prudent to only give types of service which are very clearly learning-related or support-related, clearly avoiding anything which might be considered to be intrusive vis-a-vis social conduct.

**Comment by ds10** [comment]
From call:

* David to put up examples for accessed building or facility based on accessed service

**Comment by ds10** [comment]
I've added doc and uxapi examples to 1.1.1, I'm not fully sure what the types are yet so these haven't made their way into the vocab.

**Comment by gmoger-jisc** [comment]
I will review recipe in line with data

**Comment by gmoger-jisc** [comment]
In the data we see access data we see both swipe in and out events although out events are not consistently captured across learning sites.  I don't think we could capture the in and out time as part of the same record but as separate events as that is how the source systems seem to store them, rather than as sessions.  

Can we add a field to indicate the direction of access with values IN or OUT?  What are your thoughts on this?

**Comment by ds10** [comment]
The context is for 

"An optional property that provides a place to add contextual information to a Statement."

I would think this would be ok for a context extension?

**Comment by gmoger-jisc** [comment]
Yep sure.

**Comment by ds10** [comment]
Ok, I've added the following extension to the draft recipe (in 1.1.1), but not to the vocab yet:

"http://xapi.jisc.ac.uk/extensions/direction_of_access": "**DIRECTION_OF_ACCESS**",

I'd like to talk about this at the next meeting, I'm not sure how I feel about it, but I don't really know enough about direction of access.

At the moment this can be any string(255), is that correct or should it be a boolean or from a list?

It feels like this goes against the other statements (e.g login, logout), but I don't know enough about the source systems.

**Comment by gmoger-jisc** [comment]
Can we please mint this activity type in the vocab:
**http://xapi.jisc.ac.uk/activities/learning_space**

We will only be consuming data where the student has accessed a learning space e.g. library.

This is what our template looks like currently:
```{
    "version": "1.0.0",
    "actor": {
        "objectType": "Agent",
        "account": {
            "name": "**STUDENT_ID**",
            "homePage": "https:\\**HOMEPAGE**\
        }
    },
    "timestamp": "**TIMESTAMP**",
    "verb": {
        "id": "http://activitystrea.ms/schema/1.0/access",
        "display": {
            "en": "accessed"
        }
    },
    "object": {
        "objectType": "Activity",
        "id": "https:\\**HOMEPAGE**\**SITE**",
        "definition": {
            "type": "http://xapi.jisc.ac.uk/activities/learning_space"
        }
    },
    "context": {
        "extensions": {
                "http://xapi.jisc.ac.uk/version": "1.1.1",
                "http://xapi.jisc.ac.uk/extensions/direction_of_access": "**DIRECTION_OF_ACCESS**",
                "http://xapi.jisc.ac.uk/extensions/access_id": "**ACCESS_ID**",
                "https://xapi.jisc.ac.uk/recipeCat": "Access"
        }
                
    }

}```

Can you please review?

**Comment by gmoger-jisc** [comment]
We still want to record TYPE in the input TSV as in the future this might be used to map to different activity types, but for the moment we are only interested in learning spaces (broadly defined in this way).

**Comment by ds10** [comment]
Looks ok to me, minted learning space: https://github.com/jiscdev/xapi/blob/1.1.1/vocabulary.md#learning-space but wasn't sure on your definition.

Access_id also needs minting?

**Comment by gmoger-jisc** [comment]
Yes - it is the user/student identifier from the platform and will be useful for validation purposes
