### ISSUE TITLE
Microsoft Office 365 software suite

### ISSUE THREAD

**Issue by gmoger-jisc** [jiscdev/xapi#337]
We are looking at an integration with Microsoft Office 365 to capture student engagement against different pieces of software in their subscription service.  These services and data sources have been highlighted for exploration:

Service | Use   Case | Data   Source
-- | -- | --
Teams | Last   activity date; chat, meeting and call counts | https://docs.microsoft.com/en-us/graph/api/reportroot-getteamsuseractivityuserdetail?view=graph-rest-1.0
Outlook | Last activity   date; sent, received, read counts | https://docs.microsoft.com/en-us/graph/api/reportroot-getemailactivityuserdetail?view=graph-rest-1.0
OneDrive | Last   activity date; viewed, edited, synced, shared counts | https://docs.microsoft.com/en-us/graph/api/reportroot-getonedriveactivityuserdetail?view=graph-rest-1.0
SharePoint | Same as OneDrive | https://docs.microsoft.com/en-us/graph/api/reportroot-getsharepointactivityuserdetail?view=graph-rest-1.0
Active   Directory | Sign-in   counts by app/resource | https://docs.microsoft.com/en-us/graph/api/signin-list?view=graph-rest-1.0&tabs=http
Yammer | Last activity   date; posted, read, liked counts | https://docs.microsoft.com/en-us/graph/api/reportroot-getyammeractivityuserdetail?view=graph-rest-1.0

For discussion on monthly call:
- How might engagement with these difference services be structure in xAPI?
- Is it acceptable for us to take engagement counts from the usage reports, as opposed to distinct events?

For example, something like teams might need to diverge into a number of activties:
- Student sent chat message
- Student attended virtual meeting

**Comment by gmoger-jisc** [comment]
I'm thinking it might be structured like:

**Attendance**
How to manage distinction between virtual and physical attendance?

**Communications**
Messaging services (teams chat) - read/sent/received
Discussion board (yammer) - read/posted/liked

**Login**
Logged into service (active directory) - already have recipe

**File Store**
File interaction (onedrive and sharepoint) - viewed/edited/shared

**Comment by gmoger-jisc** [comment]
July's call highlighted issues with using xAPI statements for activity aggregations and that it may be beyond the scope of the specification.  We will want to explore this further in our next call.

**Comment by ryansmith94** [comment]
Hey @gmoger-jisc. The closest thing I can find to count type statements is some statements that report KPIs.

```json
{
  "actor": {
    "objectType": "Agent",
    "mbox": "mailto:test@example.org",
    "name": "Test"
  },
  "verb": {
    "id": "http://activitystrea.ms/schema/1.0/submit",
    "display": {
      "en": "submitted"
    }
  },
  "object": {
    "objectType": "Activity",
    "id": "http://example.org/xapi/key-performance-indicators",
    "definition": {
      "name": {
        "en": "Key Performance Indicators"
      },
      "type": "http://id.tincanapi.com/activitytype/status-update"
    }
  },
  "timestamp": "2020-10-20T09:00Z",
  "result": {
    "extensions": {
      "http://learninglocker.net/xapi/extensions/kpi-1": 100,
      "http://learninglocker.net/xapi/extensions/kpi-2": 200,
      "http://learninglocker.net/xapi/extensions/kpi-3": 300
    }
  }
}
```

The closest thing I could find to Teams messages in some statements we sent for Slack messages a few years ago.

```json
{
  "actor": {
    "objectType": "Agent",
    "mbox": "mailto:test@example.org",
    "name": "Test"
  },
  "verb": {
    "id": "http://adlnet.gov/expapi/verbs/posted",
    "display": {
      "en": "posted to"
    }
  },
  "object": {
    "objectType": "Activity",
    "id": "https://test.slack.com/messages/sales-marketing",
    "definition": {
      "type": "http://id.tincanapi.com/activitytype/chat-channel",
      "name": {
        "en": "Sales Marketing"
      }
    }
  },
  "context": {
    "platform": "Slack"
  },
  "timestamp": "2020-10-20T09:00Z"
}
```

**Comment by gmoger-jisc** [comment]
This is a provision version for discussion on Monday:

Is the verb and activity type the best fit here?

`{
  "actor": {
    "objectType": "Agent",
    "account": {
        "name": "STU_12345",
        "homePage": "https://jisc-demo.ac.uk"
    }
  },
  "verb": {
    "id": "http://activitystrea.ms/schema/1.0/interact",
    "display": {
      "en": "interacted"
    }
  },
  "object": {
    "objectType": "Activity",
    "id": "http://<DOMAIN>/xapi/microsoft_aggregations_2020_10_20",
    "definition": {
      "name": {
        "en": "Microsoft Activity Aggregations"
      },
      "type": "http://xapi.jisc.ac.uk/activities/microsoft_aggregations"
    }
  },
  "context": {
    "platform": "Microsoft"
  },
  "result": {
    "extensions": {
      "http://jisc.ac.uk/microsoft/teams/teamchat": {"count": 16},
      "http://jisc.ac.uk/microsoft/teams/privatechat": {"count": 22},
      "http://jisc.ac.uk/microsoft/teams/call": {"count": 12},
      "http://jisc.ac.uk/microsoft/teams/meeting": {"count": 7},      
      "http://jisc.ac.uk/microsoft/teams/lastactivity": {"date": "2020-10-20"},
      "http://jisc.ac.uk/microsoft/onedrive/viewandedit": {"count": 76},
      "http://jisc.ac.uk/microsoft/onedrive/synced": {"count": 28},
      "http://jisc.ac.uk/microsoft/onedrive/sharedinternal": {"count": 1},
      "http://jisc.ac.uk/microsoft/onedrive/sharedexternal": {"count": 1},      
      "http://jisc.ac.uk/microsoft/onedrive/lastactivity": {"date": "2020-10-23"},
      "http://jisc.ac.uk/microsoft/sharepoint/viewandedit": {"count": 76},
      "http://jisc.ac.uk/microsoft/sharepoint/synced": {"count": 28},
      "http://jisc.ac.uk/microsoft/sharepoint/sharedinternal": {"count": 6},
      "http://jisc.ac.uk/microsoft/sharepoint/sharedexternal": {"count": 2}, 
      "http://jisc.ac.uk/microsoft/sharepoint/vistedpages": {"count": 2},        
      "http://jisc.ac.uk/microsoft/sharepoint/lastactivity": {"date": "2020-10-21"},
      "http://jisc.ac.uk/microsoft/yammer/user": {"status": "active","statuschangedate": "2020-10-18"},
      "http://jisc.ac.uk/microsoft/yammer/posted": {"count": 76},
      "http://jisc.ac.uk/microsoft/yammer/read": {"count": 28},
      "http://jisc.ac.uk/microsoft/yammer/liked": {"count": 6},
      "http://jisc.ac.uk/microsoft/yammer/lastactivity": {"date": "2020-10-18"},
      "http://jisc.ac.uk/microsoft/outlook/send": {"count": 41},
      "http://jisc.ac.uk/microsoft/outlook/receive": {"count": 39},      
      "http://jisc.ac.uk/microsoft/outlook/read": {"count": 26},
      "http://jisc.ac.uk/microsoft/outlook/lastactivity": {"date": "2020-10-18"},
      "http://jisc.ac.uk/microsoft/activedirectory/lastactivity": {"date": "2020-10-18"},
      "http://jisc.ac.uk/microsoft/activedirectory/signin": {
        "count": 41,
        "detail": {
          "Moodle": 37,
          "Panopto": 20
      }}
    }
  },
  "timestamp": "2020-10-24T09:00Z"
}`

**Comment by gmoger-jisc** [comment]
https://github.com/jiscdev/xapi/pull/341
