### ISSUE TITLE
Issues with Common Statement Properties page

### ISSUE THREAD

**Issue by arc12** [jiscdev/xapi#52]
https://github.com/jiscdev/xapi-vle/blob/master/common_statements.md

I think this page doesn't yet have clear purpose and status, and has some other issues.
- is the implication that all statements should include these fragments?
- it says "Account is the internal identifier used by the VLE." but account is a structure of 2 parts
- actor.name and actor.account.name both appear and have the same value but usage is not clarified.

Re actor: there is actually more information here https://github.com/jiscdev/xapi-vle/blob/master/recipes/login.md but I think not clarification of which name should be mapped, and some possibly-inaccurate wording about resolvability, and some need to add nuance and clarification of scope of uniqueness, persistence.

This would be a good page for an example of recipe version extension, which I couldn't see anywhere

**Comment by garemoko** [comment]
I can see common properties being useful to save having to maintain them in individual events, however it seems that this page hasn't been maintained and the information is copied across all the individual events.

**Comment by wilmTap** [comment]
I'm not sure we can make the common statement properties mandatory, because that's best determined by each recipe either using it or not. They're just re-useable fragments. 

We'll try to find a good balance between linking and replication or data management and user experience, but experience with the UDD suggests that it could be a little tricky.

**Comment by garemoko** [comment]
Either we need to maintain them and use them or delete them. Seems like deleting may be the easiest approach.

**Comment by wilmTap** [comment]
I think it's worth making it clear that fragments are the same across different recipes. We'll have a look.

**Comment by wilmTap** [comment]
Name and indicate the shared entity in each recipe.

**Comment by wilmTap** [comment]
Agreed
