### ISSUE TITLE
actor.name should either be real name or not included

### ISSUE THREAD

**Issue by garemoko** [jiscdev/xapi#67]
The actor.name should either be the person's actual name (Bob Smith) or should not be included in the case of anon data. In the case of anon data, the LRC can figure out what best to display, that's not the job of the LRP. Currently username is used here. 

Note: I'm **not** talking about actor.account.name

**Comment by wilmTap** [comment]
No strong opinion here- what do the analysts think?

**Comment by michaelwebbjisc** [comment]
From a Jisc perspective, the UDD is the definitive source of name, rather than actor.name.

**Comment by MiroslavKratchounov** [comment]
The actor.name according to the Blackboard implementation is the student first name and last name.

**Comment by wilmTap** [comment]
In the recipe: either use real.name or omit
