### ISSUE TITLE
Should xapi-vle and xapi-lib repos be merged?

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#80]
Candidate vocab: https://docs.google.com/spreadsheets/d/10xhtR9kjCSgmqk_6B4KprY4cvVUWXJctRVZaNf3lPZs/edit

**Comment by ds10** [comment]
Out of the 5 recipes in the candidate vocab, I think 2 are applications of existing ones. Added 3 draft/blank recipes for the other 3 to be developed further

**Comment by ds10** [comment]
Not sure if I've misunderstood here and included recipes required for: https://github.com/jiscdev/xapi-lib

**Comment by ds10** [comment]
Question for weekly call: Do we want to merge these repositories (this and library lib) because they will  share vocab?

**Comment by wilmTap** [comment]
Explore whether we can redirect to a generic jisc repo, or else make a human redirect.

**Comment by ds10** [comment]
This seems to be easy, I've just tried this an old repo of mine. When I changed the name of the repository the old URL redirected to the new one, so https://github.com/jiscdev/xapi-vle should send people to https://github.com/jiscdev/xapi .

Double checking before the change, are we going with  https://github.com/jiscdev/xapi

**Comment by wilmTap** [comment]
Agreed
