### ISSUE TITLE
Candidate Recipe: setting a learning target

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#83]
Taken from the [candidate vocab document](https://docs.google.com/spreadsheets/d/10xhtR9kjCSgmqk_6B4KprY4cvVUWXJctRVZaNf3lPZs/edit#gid=262364132). This ticket is for voting on where to place effort on candidate recipes (thumbs up/thumbs down).

Purpose: This activity records a user setting themselves a learning target. For example to spend a certain amount of hours reading.

Proposed verb: http://xapi.jisc.ac.uk/setAlearningTarget

**Comment by wilmTap** [comment]
May have a dependency on a privacy / access control model being developed first.
