### ISSUE TITLE
Recipe version and xapi version

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#93]
May have made a mistake here..

In the vocab document we have minted http to://xapi.jisc.ac.uk/recipeVersion for the context extensions object. The property has the description is: "Version of Recipe used. Version number can be found on recipe page". However, it doesn't seem to have made its way in to the actual recipes themselves.  Looking through previous tickets and talking this through with @wilmTap we think a weekly call decided to add recipe version to each recipe, but have somehow missed this.

Double checking before going ahead and adding recipe version number to recipes

**Comment by wilmTap** [comment]
Agreed

**Comment by ds10** [comment]
recipe versions were added and version numbers updated

**Comment by arc12** [comment]
David, all -
what I'm missing is the recipe identity.
I can see a version number, but what this is a version of doesn't seem to be specified.
i,e. I had expected metadata to say "version V of recipe R"

Without R being explicit, I suppose we could infer it from the verb, but that seems liable to be unreliable!

Did I miss something?

Adam

**Comment by ds10** [comment]
Nope, I've misunderstood!

**Comment by wilmTap** [comment]
All fixed now, and the recipes have been given UDD style normalised titles.

**Comment by wilmTap** [comment]
accepted

**Comment by MiroslavKratchounov** [comment]
@arc12  I think the combination of verb and recipe version should be reliable enough to identify and filter accordingly. I suppose we just need to have an overview of all recipes with their versions somewhere in the vocabulary. At this moment one needs to go through each recipe to get the right version.
