### ISSUE TITLE
Reading List Data

### ISSUE THREAD

**Issue by ds10** [jiscdev/xapi#98]
Do we have any examples of reading list data/logs for the [reading list viewed](https://github.com/jiscdev/xapi/blob/ds10-recipedev/recipes/reading-list-view.md) and [reading list item viewed](https://github.com/jiscdev/xapi/blob/ds10-recipedev/recipes/reading-list-item-view.md)?

**Comment by arc12** [comment]
I think it would also be instructive to look at the front-ends of reading list software too.

I suspect there is quite a range, with the minimal being just lists of resources per module with "find it in the library" links to the library catalogue or plain web links. So: we might be limited to "accessed reading list for module M", i.e. that "item viewed" is maybe a bridge too far (and would need to be clear about whether this is a reading list record for a single item in it, a hand-off to a library catalogue, or an electronic resource access.)

I also suspect that the kind of data Talis Aspire might have available is far from representative...
